### ISSUE TITLE
Trinity emits `DecodeError` during authentication

### ISSUE THREAD

**Issue by pipermerriam** [ethereum/py-evm#1017]
### What is wrong?

This stacktrace is leaking out:

```python
   ERROR  07-14 10:49:23        peer  Unexpected error during auth/p2p handshake with <Node(0x391792dc9f4d695f8f3b8b577f1fcef611d554b8b1667bf4002ebad53bc4a452d00095141ca44bb97c0a7971dee39ec0fbaebd886a0ebdfa7c7e0d8bce2e07da@34.241.35.62:30303)>
Traceback (most recent call last):
  File "/Users/piper/sites/py-evm/p2p/peer.py", line 808, in connect
    self.vm_configuration, self.cancel_token))
  File "/Users/piper/sites/py-evm/p2p/cancel_token.py", line 102, in wait
    return await self.wait_first(awaitable, token=token, timeout=timeout)
  File "/Users/piper/sites/py-evm/p2p/cancel_token.py", line 124, in wait_first
    return await wait_with_token(*awaitables, token=token_chain, timeout=timeout)
  File "/Users/piper/sites/py-evm/p2p/cancel_token.py", line 161, in wait_with_token
    return done.pop().result()
  File "/Users/piper/sites/py-evm/p2p/peer.py", line 138, in handshake
    await peer.ensure_same_side_on_dao_fork(vm_configuration)
  File "/Users/piper/sites/py-evm/p2p/peer.py", line 212, in ensure_same_side_on_dao_fork
    timeout=CHAIN_SPLIT_CHECK_TIMEOUT)
  File "/Users/piper/sites/py-evm/p2p/cancel_token.py", line 102, in wait
    return await self.wait_first(awaitable, token=token, timeout=timeout)
  File "/Users/piper/sites/py-evm/p2p/cancel_token.py", line 124, in wait_first
    return await wait_with_token(*awaitables, token=token_chain, timeout=timeout)
  File "/Users/piper/sites/py-evm/p2p/cancel_token.py", line 161, in wait_with_token
    return done.pop().result()
  File "/Users/piper/sites/py-evm/p2p/peer.py", line 668, in _get_headers_at_chain_split
    cmd, msg = await self.read_msg()
  File "/Users/piper/sites/py-evm/p2p/peer.py", line 368, in read_msg
    decoded_msg = cast(Dict[str, Any], cmd.decode(msg))
  File "/Users/piper/sites/py-evm/p2p/protocol.py", line 95, in decode
    return self.decode_payload(data[1:])
  File "/Users/piper/sites/py-evm/p2p/protocol.py", line 82, in decode_payload
    data = rlp.decode(rlp_data, sedes=decoder)
  File "/Users/piper/python-environments/evm/lib/python3.6/site-packages/rlp/codec.py", line 213, in decode
    item, end = consume_item(rlp, 0)
  File "/Users/piper/python-environments/evm/lib/python3.6/site-packages/rlp/codec.py", line 191, in consume_item
    return consume_payload(rlp, s, t, l)
  File "/Users/piper/python-environments/evm/lib/python3.6/site-packages/rlp/codec.py", line 172, in consume_payload
    item, next_item_start = consume_payload(rlp, s, t, l)
  File "/Users/piper/python-environments/evm/lib/python3.6/site-packages/rlp/codec.py", line 172, in consume_payload
    item, next_item_start = consume_payload(rlp, s, t, l)
  File "/Users/piper/python-environments/evm/lib/python3.6/site-packages/rlp/codec.py", line 171, in consume_payload
    t, l, s = consume_length_prefix(rlp, next_item_start)
  File "/Users/piper/python-environments/evm/lib/python3.6/site-packages/rlp/codec.py", line 131, in consume_length_prefix
    raise DecodingError('Encoded as short string although single byte was possible', rlp)
rlp.exceptions.DecodingError: Encoded as short string although single byte was possible
```

### How can it be fixed

Haven't investigated yet

**Comment by carver** [comment]
Looks like this should be caught in `peer.handshake()`s call to `ensure_same_side_on_dao_fork()`, then trigger a disconnect from the bad peer. (Plus logging the bad data sent by the peer, in case we're decoding something wrong).

**Comment by pipermerriam** [comment]
Duplicate of https://github.com/ethereum/py-evm/issues/1092
