### ISSUE TITLE
Unhandled `ValidationError` from ThroughputTracker

### ISSUE THREAD

**Issue by pipermerriam** [ethereum/py-evm#1037]
### What is wrong?

The `ThroughputTracker` is emitting a `ValidationError` semi-regularly.

Here are the relevant `DEBUG` logs

```
   DEBUG  07-17 16:47:52       chain  Beggining work for peer: ETHPeer <Node(0xa41d@127.0.0.1)> part: body
   DEBUG  07-17 16:47:52       chain  Requesting 121 block bodies to ETHPeer <Node(0xa41d@127.0.0.1)>
   DEBUG  07-17 16:47:52       chain  Beggining work for peer: ETHPeer <Node(0xa133@35.185.186.158)> part: body
   DEBUG  07-17 16:47:52       chain  Requesting 1 block bodies to ETHPeer <Node(0xa133@35.185.186.158)>
   DEBUG  07-17 16:47:52        peer  Could not complete handshake with <Node(0x399c7559da25f765b3590d974a852560b3e1467b5d926aac482debe2aaa39b5b6d35df92b41514fef5d3b6907ec9a2f21811c089f0ef8d14a2fc45a616bc720e@13.251.66.118:30305)>: HandshakeFailure('ETHPeer <Node(0x399c@13.251.66.118)> disconnected before completing handshake: too_many_peers',)
   DEBUG  07-17 16:47:52       chain  Got Bodies for 121 blocks from ETHPeer <Node(0xa41d@127.0.0.1)>
   DEBUG  07-17 16:47:52       chain  Got Bodies for 1 blocks from ETHPeer <Node(0xa133@35.185.186.158)>
   DEBUG  07-17 16:47:52       chain  Completing work for peer: ETHPeer <Node(0xa133@35.185.186.158)> part: BlockPartEnum.body
   DEBUG  07-17 16:47:52        peer  ETHPeer <Node(0xa41d@127.0.0.1)> disconnected: useless_peer
    INFO  07-17 16:47:52        peer  ETHPeer <Node(0xa41d@127.0.0.1)> finished, removing from pool
   DEBUG  07-17 16:47:52        peer  Could not complete handshake with <Node(0xcce09bd1ab7c00ee07613a4b40a84f858e85611ec98d9f836da19074777aca2f1c97583500197d6c5d969444d1d9b8bcc02afff4442f608b203d8447653b4f63@18.182.24.209:30303)>: HandshakeFailure('ETHPeer <Node(0xcce0@18.182.24.209)> disconnected before completing handshake: too_many_peers',)
   DEBUG  07-17 16:47:52        peer  Could not complete handshake with <Node(0xac22b0fc0e25febcfcc81040fffe67d663fa492635b0f7a96061e2ed6ae3771714b542395a5df76c97e20068f4cfb66056dd04af96f6f041345f382e41ee5db2@149.28.108.149:30303)>: HandshakeFailure('ETHPeer <Node(0xac22@149.28.108.149)> disconnected before completing handshake: too_many_peers',)
   DEBUG  07-17 16:47:53       chain  Completing work for peer: ETHPeer <Node(0xa41d@127.0.0.1)> part: BlockPartEnum.body
   ERROR  07-17 16:47:53  base_events  Task exception was never retrieved
future: <Task finished coro=<BaseHeaderChainSyncer.sync() done, defined at /Users/piper/sites/py-evm/p2p/chain.py:156> exception=ValidationError('Cannot end the ThroughputTracker without starting it',)>
Traceback (most recent call last):
  File "/Users/piper/sites/py-evm/p2p/chain.py", line 169, in sync
    await self._sync(peer)
  File "/Users/piper/sites/py-evm/p2p/chain.py", line 230, in _sync
    head_number = await self._process_headers(peer, headers)
  File "/Users/piper/sites/py-evm/p2p/chain.py", line 376, in _process_headers
    BlockPartEnum.body,
  File "/Users/piper/sites/py-evm/p2p/chain.py", line 452, in _download_block_parts
    self._get_peer_stats(peer, part_name).complete_work(work_size)
  File "/Users/piper/sites/py-evm/p2p/utils.py", line 84, in complete_work
    raise ValidationError("Cannot end the ThroughputTracker without starting it")
eth.exceptions.ValidationError: Cannot end the ThroughputTracker without starting it
```

These logs show that the node `0xa41d` disconnects shortly after sending through a requested batch of work.  The disconnect is processed before the received bodies are processed, which causes `deregister_peer` to be called.  This causes the `ThroughputTracker` for the given peer to be cleared.  Then, when the work is received and processed, it encounters a fresh (lazily created) `ThroughputTracker` which has not had work started on it, causing the exception.

### How can it be fixed

Maybe:

1. silently ignore this when it happens (has high likelyhood of silencing real errors)
2. don't clear trackers immediately on disconnect
3. don't clear trackers at all and instead use a TTL expiration mechanism to automatically clear trackers which are *old*.
4. modify the trackers to not be singletons but to be able to track multiple in-flight requests concurrently.  Key the requests based on some kind of unique-ish request identifier based on what was requested to ensure that the `complete_work` is being called on the actual request that started the work.  use a TTL mechanism to expire timed out requests as well as timed out trackers.

Last idea in list is my favorite

**Comment by carver** [comment]
Yeah, option 4 (roughly) is probably where we were headed anyway to get #868 closed.

In the meantime, for grace hopper I am pretty tempted to do option 1. The worst case is that we drop some data that we didn't have at all before the throughput tracker existed.

**Comment by pipermerriam** [comment]
👍 to doing option 1 and prioritizing option 2 for the next major release.
