### ISSUE TITLE
fix-unclean-shutdown doesn't seem to help here

### ISSUE THREAD

**Issue by cburgdorf** [ethereum/py-evm#1040]
### What is wrong?

Need to investigate further, just a quick dump to not forget.

```
$ trinity
    INFO  07-18 11:52:50        main  
      ______     _       _ __       
     /_  __/____(_)___  (_) /___  __
      / / / ___/ / __ \/ / __/ / / /
     / / / /  / / / / / / /_/ /_/ / 
    /_/ /_/  /_/_/ /_/_/\__/\__, /  
                           /____/   
    INFO  07-18 11:52:50        main  Trinity/0.2.0a26/linux/cpython3.6.5
    INFO  07-18 11:52:50        main  Trinity DEBUG log file is created at /home/cburgdorf/.local/share/trinity/mainnet/logs/trinity.log
    INFO  07-18 11:52:50        main  Started DB server process (pid=27313)
    INFO  07-18 11:52:50        main  Started networking process (pid=27314)
Process SpawnProcess-1:
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/cburgdorf/Documents/hacking/ef/py-evm/trinity/utils/profiling.py", line 31, in inner
    return fn(*args, **kwargs)
  File "/home/cburgdorf/Documents/hacking/ef/py-evm/trinity/utils/logging.py", line 118, in inner
    return fn(*args, **inner_kwargs)
  File "/home/cburgdorf/Documents/hacking/ef/py-evm/trinity/main.py", line 249, in run_database_process
    serve_chaindb(chain_config, base_db)
  File "/home/cburgdorf/Documents/hacking/ef/py-evm/trinity/chains/__init__.py", line 258, in serve_chaindb
    server = manager.get_server()  # type: ignore
  File "/usr/lib/python3.6/multiprocessing/managers.py", line 482, in get_server
    self._authkey, self._serializer)
  File "/usr/lib/python3.6/multiprocessing/managers.py", line 139, in __init__
    self.listener = Listener(address=address, backlog=16)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 438, in __init__
    self._listener = SocketListener(address, family, backlog)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 576, in __init__
    self._socket.bind(address)
OSError: [Errno 98] Address already in use
Process SpawnProcess-2:
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/cburgdorf/Documents/hacking/ef/py-evm/trinity/utils/profiling.py", line 31, in inner
    return fn(*args, **kwargs)
  File "/home/cburgdorf/Documents/hacking/ef/py-evm/trinity/utils/logging.py", line 118, in inner
    return fn(*args, **inner_kwargs)
  File "/home/cburgdorf/Documents/hacking/ef/py-evm/trinity/main.py", line 288, in launch_node
    node = NodeClass(plugin_manager, chain_config)
  File "/home/cburgdorf/Documents/hacking/ef/py-evm/trinity/nodes/full.py", line 26, in __init__
    super().__init__(plugin_manager, chain_config)
  File "/home/cburgdorf/Documents/hacking/ef/py-evm/trinity/nodes/base.py", line 63, in __init__
    self._db_manager.connect()  # type: ignore
  File "/usr/lib/python3.6/multiprocessing/managers.py", line 489, in connect
    conn = Client(self._address, authkey=self._authkey)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 487, in Client
    c = SocketClient(address)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 614, in SocketClient
    s.connect(address)
ConnectionRefusedError: [Errno 111] Connection refused
(venv) cburgdorf at craftbot in ~/Documents/hacking/ef/py-evm on christoph/tests/trinity-integration*
$ trinity fix-unclean-shutdown
    INFO  07-18 11:53:10        main  Cleaning up unclean shutdown...
    INFO  07-18 11:53:10        main  Found 0 processes from a previous run. Nothing to do.
(venv) cburgdorf at craftbot in ~/Documents/hacking/ef/py-evm on christoph/tests/trinity-integration*
$ trinity
    INFO  07-18 11:53:16        main  
      ______     _       _ __       
     /_  __/____(_)___  (_) /___  __
      / / / ___/ / __ \/ / __/ / / /
     / / / /  / / / / / / /_/ /_/ / 
    /_/ /_/  /_/_/ /_/_/\__/\__, /  
                           /____/   
    INFO  07-18 11:53:16        main  Trinity/0.2.0a26/linux/cpython3.6.5
    INFO  07-18 11:53:16        main  Trinity DEBUG log file is created at /home/cburgdorf/.local/share/trinity/mainnet/logs/trinity.log
    INFO  07-18 11:53:16        main  Started DB server process (pid=27441)
    INFO  07-18 11:53:16        main  Started networking process (pid=27442)
Process SpawnProcess-2:
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/cburgdorf/Documents/hacking/ef/py-evm/trinity/utils/profiling.py", line 31, in inner
    return fn(*args, **kwargs)
  File "/home/cburgdorf/Documents/hacking/ef/py-evm/trinity/utils/logging.py", line 118, in inner
    return fn(*args, **inner_kwargs)
  File "/home/cburgdorf/Documents/hacking/ef/py-evm/trinity/main.py", line 288, in launch_node
    node = NodeClass(plugin_manager, chain_config)
  File "/home/cburgdorf/Documents/hacking/ef/py-evm/trinity/nodes/full.py", line 26, in __init__
    super().__init__(plugin_manager, chain_config)
  File "/home/cburgdorf/Documents/hacking/ef/py-evm/trinity/nodes/base.py", line 63, in __init__
    self._db_manager.connect()  # type: ignore
  File "/usr/lib/python3.6/multiprocessing/managers.py", line 489, in connect
    conn = Client(self._address, authkey=self._authkey)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 487, in Client
    c = SocketClient(address)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 614, in SocketClient
    s.connect(address)
ConnectionRefusedError: [Errno 111] Connection refused
Process SpawnProcess-1:
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/cburgdorf/Documents/hacking/ef/py-evm/trinity/utils/profiling.py", line 31, in inner
    return fn(*args, **kwargs)
  File "/home/cburgdorf/Documents/hacking/ef/py-evm/trinity/utils/logging.py", line 118, in inner
    return fn(*args, **inner_kwargs)
  File "/home/cburgdorf/Documents/hacking/ef/py-evm/trinity/main.py", line 249, in run_database_process
    serve_chaindb(chain_config, base_db)
  File "/home/cburgdorf/Documents/hacking/ef/py-evm/trinity/chains/__init__.py", line 258, in serve_chaindb
    server = manager.get_server()  # type: ignore
  File "/usr/lib/python3.6/multiprocessing/managers.py", line 482, in get_server
    self._authkey, self._serializer)
  File "/usr/lib/python3.6/multiprocessing/managers.py", line 139, in __init__
    self.listener = Listener(address=address, backlog=16)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 438, in __init__
    self._listener = SocketListener(address, family, backlog)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 576, in __init__
    self._socket.bind(address)
OSError: [Errno 98] Address already in use
```

### How can it be fixed

:see_no_evil: :hear_no_evil:

**Comment by cburgdorf** [comment]
In this case, it was the `db.ipc` that was left behind and caused the `Address already in use` issue.

**Comment by carver** [comment]
> In this case, it was the db.ipc that was left behind and caused the Address already in use issue.

Which isn't one of the fixes yet. A line that removes that file can be added to the end of `fix_unclean_shutdown(chain_config: ChainConfig, logger: logging.Logger)` in trinity/main

(The end, because we want to give the processes a chance to shut down, first.
