### ISSUE TITLE
rlp decoding error crashes `DiscoveryService`

### ISSUE THREAD

**Issue by pipermerriam** [ethereum/py-evm#1092]
### What is wrong?

The discovery service crashed because of an `rlp.DecodingError`

```
Traceback (most recent call last):
  File "/home/piper/projects/py-evm/p2p/service.py", line 60, in run
    await self._run()
  File "/home/piper/projects/py-evm/p2p/discovery.py", line 339, in _run
    await self.maybe_connect_to_more_peers()
  File "/home/piper/projects/py-evm/p2p/discovery.py", line 351, in maybe_connect_to_more_peers
    self.proto.get_nodes_to_connect(self.peer_pool.max_peers))
  File "/home/piper/projects/py-evm/p2p/peer.py", line 937, in connect_to_nodes
    await self.start_peer(peer)
  File "/home/piper/projects/py-evm/p2p/peer.py", line 852, in start_peer
    msgs = await self.ensure_same_side_on_dao_fork(peer)
  File "/home/piper/projects/py-evm/p2p/peer.py", line 965, in ensure_same_side_on_dao_fork
    while True:
  File "/home/piper/projects/py-evm/p2p/cancel_token.py", line 102, in wait
    return await self.wait_first(awaitable, token=token, timeout=timeout)
  File "/home/piper/projects/py-evm/p2p/cancel_token.py", line 124, in wait_first
    return await wait_with_token(*awaitables, token=token_chain, timeout=timeout)
  File "/home/piper/projects/py-evm/p2p/cancel_token.py", line 161, in wait_with_token
    return done.pop().result()
  File "/home/piper/projects/py-evm/p2p/peer.py", line 448, in read_msg
    decoded_msg = cast(Dict[str, Any], cmd.decode(msg))
  File "/home/piper/projects/py-evm/p2p/protocol.py", line 97, in decode
    return self.decode_payload(data[1:])
  File "/home/piper/projects/py-evm/p2p/protocol.py", line 84, in decode_payload
    data = rlp.decode(rlp_data, sedes=decoder)
  File "/home/piper/python-environments/evm/lib/python3.6/site-packages/rlp/codec.py", line 213, in decode
    item, end = consume_item(rlp, 0)
  File "/home/piper/python-environments/evm/lib/python3.6/site-packages/rlp/codec.py", line 191, in consume_item
    return consume_payload(rlp, s, t, l)
  File "/home/piper/python-environments/evm/lib/python3.6/site-packages/rlp/codec.py", line 172, in consume_payload
    item, next_item_start = consume_payload(rlp, s, t, l)
  File "/home/piper/python-environments/evm/lib/python3.6/site-packages/rlp/codec.py", line 172, in consume_payload
    item, next_item_start = consume_payload(rlp, s, t, l)
  File "/home/piper/python-environments/evm/lib/python3.6/site-packages/rlp/codec.py", line 171, in consume_payload
    t, l, s = consume_length_prefix(rlp, next_item_start)
  File "/home/piper/python-environments/evm/lib/python3.6/site-packages/rlp/codec.py", line 131, in consume_length_prefix
    raise DecodingError('Encoded as short string although single byte was possible', rlp)
rlp.exceptions.DecodingError: Encoded as short string although single byte was possible
```

### How can it be fixed

Not sure yet

**Comment by pipermerriam** [comment]
cc @gsalgado thoughts on where to correctly handle this?

**Comment by gsalgado** [comment]
I think either `Protocol.decode_payload()` or `BasePeer.read_msg()` would be fine, but the former is probably better as it's the closest to the actual source of the exception. We should also log the msg itself as it might be a bug in our rlp library, right?

**Comment by pipermerriam** [comment]
>  it might be a bug in our rlp library, right?

Possibly but unlikely.  Need to check the tests, but there is a reasonably exhaustive and easy to make check for whether something should be encoded as a single character.

**Comment by pipermerriam** [comment]
https://github.com/ethereum/pyrlp/blob/master/rlp/codec.py#L128-L132

Looks correct to me.  Checks if the encoded length is `1` and whether the encoded byte is `< 128` which indicates it should have been encoded as a single byte (without the length prefix).
