### ISSUE TITLE
Fails to install

### ISSUE THREAD

**Issue by pyrex41** [ethereum/py-evm#1153]
* py-evm Version: 0.1.0
* OS: osx
* Python Version (python --version): python 3.7
* Environment (output of `pip freeze`):
atomicwrites==1.1.5
attrdict==2.0.0
attrs==18.1.0
certifi==2018.4.16
chardet==3.0.4
cytoolz==0.9.0.1
eth-abi==1.1.1
eth-account==0.3.0
eth-hash==0.1.4
eth-keyfile==0.5.1
eth-keys==0.2.0b3
eth-rlp==0.1.2
eth-tester==0.1.0b30
eth-utils==1.0.3
eth-vyper==0.1.0b2
hexbytes==0.1.0
idna==2.7
lru-dict==1.1.6
more-itertools==4.3.0
parsimonious==0.8.1
pluggy==0.7.1
py==1.5.4
pycryptodome==3.6.4
pytest==3.7.1
requests==2.19.1
rlp==1.0.2
scrypt==0.8.6
semantic-version==2.6.0
six==1.11.0
toolz==0.9.0
urllib3==1.23
web3==4.5.0
websockets==6.0

### What is wrong?
Does not install; suspect issue with python 3.7?

run from inside virtual-env:
`pip3 install py-evm
`
Output:
```
Collecting py-evm
  Using cached https://files.pythonhosted.org/packages/1b/fd/ac0671e43cd1658695e1d5c516a84f681c9fcfd47145e88f775724fe413a/py-evm-0.1.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/p7/c9bfbv7j1szg4v4vtqqqgyyw0000gn/T/pip-install-9k657l_b/py-evm/setup.py", line 11, in <module>
        readme = open(os.path.join(DIR, 'README.md')).read()
    FileNotFoundError: [Errno 2] No such file or directory: '/private/var/folders/p7/c9bfbv7j1szg4v4vtqqqgyyw0000gn/T/pip-install-9k657l_b/py-evm/README.md'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/p7/c9bfbv7j1szg4v4vtqqqgyyw0000gn/T/pip-install-9k657l_b/py-evm/
Please include information like:
```

**Comment by dylanjw** [comment]
https://github.com/ethereum/py-evm/pull/1109 updates a few dependencies that were preventing py-evm from installing with python3.7.  You would need to either install from master or update the plylevel to 1.0.5 and coincurve to >=8.0.0 in your virtualenv.


```
git clone git@github.com:ethereum/py-evm.git
cd py-evm
pip install -e .
```
