### ISSUE TITLE
StateDownloader._request_and_process_nodes must catch OperationCancelled

### ISSUE THREAD

**Issue by gsalgado** [ethereum/py-evm#1162]
That method runs as a background task (via `asyncio.ensure_future()`) so it must catch and handle `OperationCancelled`, like, e.g., `_periodically_retry_timedout_and_missing()`

```
2018-08-09 18:49:29,637 ERROR: Task exception was never retrieved
future: <Task finished coro=<StateDownloader._request_and_process_nodes() done, defined at /home/salgado/src/py-evm/trinity/sync/full/state.py:237> exception=OperationCancelled('Cancellation requested by ETHRequestResponseHandler:ETHPeer:PeerPool token',)>
Traceback (most recent call last):
  File "/home/salgado/src/py-evm/trinity/sync/full/state.py", line 239, in _request_and_process_nodes
    node_data = await peer.requests.get_node_data(batch)
  File "/home/salgado/src/py-evm/trinity/protocol/eth/managers.py", line 94, in __call__
    return await self._request_and_wait(request, timeout)
  File "/home/salgado/src/py-evm/trinity/protocol/common/managers.py", line 173, in _request_and_wait
    return await self._wait_for_response(request, timeout=timeout)
  File "/home/salgado/src/py-evm/trinity/protocol/common/managers.py", line 162, in _wait_for_response
    response = await self.wait(future, timeout=timeout)
  File "/home/salgado/src/py-evm/p2p/cancellable.py", line 19, in wait
    return await self.wait_first(awaitable, token=token, timeout=timeout)
  File "/home/salgado/src/py-evm/p2p/cancellable.py", line 41, in wait_first
    return await token_chain.cancellable_wait(*awaitables, timeout=timeout)
  File "/home/salgado/virtualenvs/pyevm/lib/python3.6/site-packages/cancel_token/token.py", line 150, in cancellable_wait
    "Cancellation requested by {} token".format(self.triggered_token)
cancel_token.exceptions.OperationCancelled: Cancellation requested by ETHRequestResponseHandler:ETHPeer:PeerPool token
```

**Comment by pipermerriam** [comment]
I added this to the release for next week.
