### ISSUE TITLE
ValidationError escaping during regular sync

### ISSUE THREAD

**Issue by pipermerriam** [ethereum/py-evm#1185]
### What is wrong?

I encountered the following `ValidationError` during regular sync.  The error persisted through a restart of the node and I ended up using fast sync to get past it.

```python
   ERROR  08-14 19:57:09  base_events  Task exception was never retrieved
future: <Task finished coro=<BaseService.run_task.<locals>.f() done, defined at /home/piper/projects/py-evm/p2p/service.py:129> exception=ValidationError('Uncle 0x70a2595cb8b954489d23fdca685ab59b86a874ba37b9a5902cf480e44ab10a1c cannot be an ancestor of 0xbc1e1e2e7a1cd1cd9749fdc9ac65b4a1f66c943f0388ebb66c0d887ddb0b41c5',)>
trinity.chains.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/piper/projects/py-evm/trinity/chains/__init__.py", line 178, in wrapper
    return attr(*args, **kwargs)
  File "/home/piper/projects/py-evm/eth/chains/base.py", line 609, in import_block
    self.validate_block(imported_block)
  File "/home/piper/projects/py-evm/eth/chains/base.py", line 637, in validate_block
    self.validate_uncles(block)
  File "/home/piper/projects/py-evm/eth/chains/base.py", line 699, in validate_uncles
    encode_hex(uncle.hash), encode_hex(block.hash)))
eth.exceptions.ValidationError: Uncle 0x70a2595cb8b954489d23fdca685ab59b86a874ba37b9a5902cf480e44ab10a1c cannot be an ancestor of 0xbc1e1e2e7a1cd1cd9749fdc9ac65b4a1f66c943f0388ebb66c0d887ddb0b41c5
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/piper/projects/py-evm/p2p/service.py", line 131, in f
    await awaitable
  File "/home/piper/projects/py-evm/trinity/sync/common/chain.py", line 127, in sync
    await self._sync(peer)
  File "/home/piper/projects/py-evm/trinity/sync/common/chain.py", line 194, in _sync
    head_number = await self._process_headers(peer, headers)
  File "/home/piper/projects/py-evm/trinity/sync/full/chain.py", line 386, in _process_headers
    await self.wait(self.chain.coro_import_block(block, perform_validation=True))
  File "/home/piper/projects/py-evm/p2p/cancellable.py", line 19, in wait
    return await self.wait_first(awaitable, token=token, timeout=timeout)
  File "/home/piper/projects/py-evm/p2p/cancellable.py", line 41, in wait_first
    return await token_chain.cancellable_wait(*awaitables, timeout=timeout)
  File "/home/piper/python-environments/evm/lib/python3.6/site-packages/cancel_token/token.py", line 152, in cancellable_wait
    return done.pop().result()
  File "/home/piper/projects/py-evm/trinity/utils/mp.py", line 31, in method
    args,
  File "/home/piper/.pyenv/versions/3.6.5/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/piper/.pyenv/versions/3.6.5/lib/python3.6/multiprocessing/managers.py", line 772, in _callmethod
    raise convert_to_error(kind, result)
eth.exceptions.ValidationError: Uncle 0x70a2595cb8b954489d23fdca685ab59b86a874ba37b9a5902cf480e44ab10a1c cannot be an ancestor of 0xbc1e1e2e7a1cd1cd9749fdc9ac65b4a1f66c943f0388ebb66c0d887ddb0b41c5
```

Full logs here: https://gist.github.com/pipermerriam/f33802d8d8890af3c6c7a128e2745e75/raw/b1c03d319ff3c9fc2c36fdcf11b7b5a96e2fbd60/trinity-uncle-validation-error.log

The block which caused the error: https://etherscan.io/block/0xbc1e1e2e7a1cd1cd9749fdc9ac65b4a1f66c943f0388ebb66c0d887ddb0b41c5

### How can it be fixed

Don't know yet.

**Comment by pipermerriam** [comment]
The code throwing the error is here: 

https://github.com/ethereum/py-evm/blob/bab7b8a46542acb333f7164e91d9954a26198acb/eth/chains/base.py#L689-L693

It suggests that py-evm *thinks* that the uncle hash in question is actually a cononical ancestor block.

**Comment by pipermerriam** [comment]
Interesting.  I think I see what is happening.  The *ancestor* and the *uncle* are both at the same height.  What I think we are seeing is a chain re-org where the existing chain `HEAD` block is being re-organized to be an uncle.

We'll need to update that validation logic to take this situation into account.  Currently we pull ancestor hashes by looking up the canonical block for a given number.  I think we need to change this to instead trace back through the parent hashes because during block validation we only actually care about the chain of blocks that the new block is part of, not the canonical chain.
