### ISSUE TITLE
Invalid canonical address

### ISSUE THREAD

**Issue by paymog** [ethereum/py-evm#1203]
* py-evm Version: 0.2.0a26
* OS: osx
* Python Version (python --version): Python 3.6.5
* Environment (output of `pip freeze`):
```
aiohttp==2.3.10
amqp==2.3.2
aniso8601==3.0.2
appnope==0.1.0
asn1crypto==0.24.0
async-lru==0.1.0
async-timeout==3.0.0
attrdict==2.0.0
backcall==0.1.0
billiard==3.5.0.4
bitcoin==1.1.42
celery==4.2.0
certifi==2018.4.16
cffi==1.11.5
chardet==3.0.4
click==6.7
coincurve==7.1.0
coverage==4.5.1
cryptography==2.3.1
cytoolz==0.9.0.1
decorator==4.3.0
dj-database-url==0.5.0
Django==2.0.6
django-celery-beat==1.1.1
django-celery-results==1.0.1
django-cors-headers==2.3.0
eth-abi==1.1.1
eth-account==0.2.3
eth-bloom==1.0.0
eth-hash==0.1.4
eth-keyfile==0.5.1
eth-keys==0.2.0b3
eth-rlp==0.1.2
eth-tester==0.1.0b27
eth-utils==1.0.3
Flask==1.0.2
Flask-GraphQL==1.4.1
graphene==2.1
graphene-django==2.0.0
graphql-core==2.0
graphql-relay==0.4.5
hexbytes==0.1.0
idna==2.7
idna-ssl==1.1.0
ipython==6.5.0
ipython-genutils==0.2.0
iso8601==0.1.12
itsdangerous==0.24
jedi==0.12.1
Jinja2==2.10
kombu==4.2.1
lru-dict==1.1.6
lxml==4.2.4
MarkupSafe==1.0
multidict==4.3.1
netdisco==2.0.0
netifaces==0.10.7
parsimonious==0.8.0
parso==0.3.1
pbkdf2==1.3
pexpect==4.6.0
pickleshare==0.7.4
plyvel==1.0.4
promise==2.1
prompt-toolkit==1.0.15
psycopg2==2.7.5
psycopg2-binary==2.7.5
ptyprocess==0.6.0
py-ecc==1.4.3
py-evm==0.2.0a26
py-solc==3.1.0
pycparser==2.18
pycryptodome==3.6.1
pyethash==0.1.27
PyGithub==1.40
Pygments==2.2.0
PyJWT==1.6.4
pysha3==1.0.2
python-dateutil==2.7.3
pytz==2018.5
PyYAML==3.12
redis==2.10.6
repoze.lru==0.7
requests==2.19.1
rlp==1.0.2
Rx==1.6.1
scrypt==0.8.6
secp256k1==0.13.2
semantic-version==2.6.0
simplegeneric==0.8.1
singledispatch==3.4.0.3
six==1.11.0
SQLAlchemy==1.2.9
toolz==0.9.0
traitlets==4.3.2
trie==1.3.8
typing==3.6.4
uPnPClient==0.0.8
urllib3==1.23
vine==1.1.4
wcwidth==0.1.7
web3==4.3.0
websockets==4.0.1
Werkzeug==0.14.1
yarl==1.2.6
zeroconf==0.20.0
```
### What is wrong?
The following code worked flawlessly with `pyethereum` but now I'm getting the following error: `evm.exceptions.ValidationError: Storage Address 0x7E5F4552091A69125d5DfCb7b8C2659029395Bdf is not a valid canonical address`

```
W3 = Web3(EthereumTesterProvider(PyEVMBackend()))

class TestBaseDao(unittest.TestCase):

    def test(self):
        # constants.COMPILER is a class I wrote which performs contract compilation
        base_dao_interface = constants.COMPILER.get_contract_interface("base_dao.sol", "BaseDao")
        contract = W3.eth.contract(abi=contract_interface['abi'], bytecode=contract_interface['bin']           
        
        # this is the line that fails
        tx_hash = contract.constructor().transact(transaction={'from': W3.eth.accounts[0]}) 
        tx_receipt = W3.eth.waitForTransactionReceipt(tx_hash, timeout=timeout)
        contract_address = tx_receipt['contractAddress']

        abi = contract_interface['abi']
        contract_instance = W3.eth.contract(address=contract_address, abi=abi,
                                        ContractFactoryClass=ConciseContract)

        # need to recreate the contract now that we've successfully deployed and have a contract address
        contract = W3.eth.contract(address=contract_address, abi=contract_interface['abi'])
```

Here's the full output of the error:

```
Testing started at 5:25 PM ...
/Users/paymahn/mycro/backend/venv/bin/python /Applications/PyCharm.app/Contents/helpers/pycharm/_jb_unittest_runner.py --target test_base_dao.TestBaseDao.test_can_propose
Launching unittests with arguments python -m unittest test_base_dao.TestBaseDao.test_can_propose in /Users/paymahn/mycro/backend/tests/contracts


Ran 1 test in 0.368s

FAILED (errors=1)

Error
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/unittest/case.py", line 601, in run
    self.setUp()
  File "/Users/paymahn/mycro/backend/tests/contracts/test_base_dao.py", line 27, in setUp
    INITIAL_ADDRESSES, INITIAL_BALANCES)
  File "/Users/paymahn/mycro/backend/server/utils/deploy.py", line 106, in _deploy_contract
    tx_hash = contract.constructor(*args).transact(transaction={'from': w3.eth.accounts[0]})
  File "/Users/paymahn/mycro/backend/venv/lib/python3.6/site-packages/web3/utils/decorators.py", line 14, in _wrapper
    return self.method(obj, *args, **kwargs)
  File "/Users/paymahn/mycro/backend/venv/lib/python3.6/site-packages/web3/contract.py", line 842, in transact
    return self.web3.eth.sendTransaction(transact_transaction)
  File "/Users/paymahn/mycro/backend/venv/lib/python3.6/site-packages/web3/eth.py", line 262, in sendTransaction
    get_buffered_gas_estimate(self.web3, transaction),
  File "/Users/paymahn/mycro/backend/venv/lib/python3.6/site-packages/web3/utils/transactions.py", line 84, in get_buffered_gas_estimate
    gas_estimate = web3.eth.estimateGas(gas_estimate_transaction)
  File "/Users/paymahn/mycro/backend/venv/lib/python3.6/site-packages/web3/eth.py", line 303, in estimateGas
    [transaction],
  File "/Users/paymahn/mycro/backend/venv/lib/python3.6/site-packages/web3/manager.py", line 107, in request_blocking
    response = self._make_request(method, params)
  File "/Users/paymahn/mycro/backend/venv/lib/python3.6/site-packages/web3/manager.py", line 90, in _make_request
    return request_func(method, params)
  File "/Users/paymahn/mycro/backend/venv/lib/python3.6/site-packages/web3/middleware/gas_price_strategy.py", line 18, in middleware
    return make_request(method, params)
  File "cytoolz/functoolz.pyx", line 232, in cytoolz.functoolz.curry.__call__
  File "/Users/paymahn/mycro/backend/venv/lib/python3.6/site-packages/web3/middleware/formatting.py", line 48, in apply_formatters
    response = make_request(method, formatted_params)
  File "/Users/paymahn/mycro/backend/venv/lib/python3.6/site-packages/web3/middleware/attrdict.py", line 18, in middleware
    response = make_request(method, params)
  File "cytoolz/functoolz.pyx", line 232, in cytoolz.functoolz.curry.__call__
  File "/Users/paymahn/mycro/backend/venv/lib/python3.6/site-packages/web3/middleware/formatting.py", line 48, in apply_formatters
    response = make_request(method, formatted_params)
  File "/Users/paymahn/mycro/backend/venv/lib/python3.6/site-packages/web3/middleware/normalize_errors.py", line 9, in middleware
    result = make_request(method, params)
  File "cytoolz/functoolz.pyx", line 232, in cytoolz.functoolz.curry.__call__
  File "/Users/paymahn/mycro/backend/venv/lib/python3.6/site-packages/web3/middleware/formatting.py", line 48, in apply_formatters
    response = make_request(method, formatted_params)
  File "cytoolz/functoolz.pyx", line 232, in cytoolz.functoolz.curry.__call__
  File "/Users/paymahn/mycro/backend/venv/lib/python3.6/site-packages/web3/middleware/formatting.py", line 48, in apply_formatters
    response = make_request(method, formatted_params)
  File "/Users/paymahn/mycro/backend/venv/lib/python3.6/site-packages/web3/providers/eth_tester/middleware.py", line 320, in middleware
    return make_request(method, [filled_transaction] + params[1:])
  File "/Users/paymahn/mycro/backend/venv/lib/python3.6/site-packages/web3/middleware/fixture.py", line 12, in middleware
    return make_request(method, params)
  File "cytoolz/functoolz.pyx", line 232, in cytoolz.functoolz.curry.__call__
  File "/Users/paymahn/mycro/backend/venv/lib/python3.6/site-packages/web3/middleware/formatting.py", line 48, in apply_formatters
    response = make_request(method, formatted_params)
  File "/Users/paymahn/mycro/backend/venv/lib/python3.6/site-packages/web3/providers/eth_tester/main.py", line 46, in make_request
    response = delegator(self.ethereum_tester, params)
  File "cytoolz/functoolz.pyx", line 232, in cytoolz.functoolz.curry.__call__
  File "/Users/paymahn/mycro/backend/venv/lib/python3.6/site-packages/web3/providers/eth_tester/defaults.py", line 36, in call_eth_tester
    return getattr(eth_tester, fn_name)(*fn_args, **fn_kwargs)
  File "/Users/paymahn/mycro/backend/venv/lib/python3.6/site-packages/eth_tester/utils/formatting.py", line 85, in wrapper
    return to_wrap(*args, **kwargs)
  File "/Users/paymahn/mycro/backend/venv/lib/python3.6/site-packages/eth_tester/backends/pyevm/main.py", line 488, in estimate_gas
    transaction, 'gas', 21000))
  File "/Users/paymahn/mycro/backend/venv/lib/python3.6/site-packages/eth_tester/backends/pyevm/main.py", line 449, in _get_normalized_and_unsigned_evm_transaction
    normalized_transaction = self._normalize_transaction(transaction, block_number)
  File "/Users/paymahn/mycro/backend/venv/lib/python3.6/site-packages/eth_utils/functional.py", line 22, in inner
    return callback(fn(*args, **kwargs))
  File "/Users/paymahn/mycro/backend/venv/lib/python3.6/site-packages/eth_tester/backends/pyevm/main.py", line 438, in _normalize_transaction
    yield 'nonce', self.get_nonce(transaction['from'], block_number)
  File "/Users/paymahn/mycro/backend/venv/lib/python3.6/site-packages/eth_tester/backends/pyevm/main.py", line 418, in get_nonce
    return vm.state.account_db.get_nonce(account)
  File "/Users/paymahn/mycro/backend/venv/lib/python3.6/site-packages/evm/db/account.py", line 286, in get_nonce
    validate_canonical_address(address, title="Storage Address")
  File "/Users/paymahn/mycro/backend/venv/lib/python3.6/site-packages/evm/validation.py", line 109, in validate_canonical_address
    "{title} {0} is not a valid canonical address".format(value, title=title)
evm.exceptions.ValidationError: Storage Address 0x7E5F4552091A69125d5DfCb7b8C2659029395Bdf is not a valid canonical address


Process finished with exit code 1
```

Before moving to `py-evm` I had the following `requirements.txt` and didn't initialize `Web3` with `PyEVMBackend` but still used `EthereumTesterProvider`: 
```
amqp==2.3.2
aniso8601==3.0.2
attrdict==2.0.0
billiard==3.5.0.4
bitcoin==1.1.42
celery==4.2.0
certifi==2018.4.16
cffi==1.11.5
chardet==3.0.4
click==6.7
coverage==4.5.1
cytoolz==0.9.0.1
dj-database-url==0.5.0
Django==2.0.6
django-celery-beat==1.1.1
django-celery-results==1.0.1
django-cors-headers==2.3.0
eth-abi==1.1.1
eth-account==0.2.3
eth-hash==0.1.4
eth-keyfile==0.5.1
eth-keys==0.2.0b3
eth-rlp==0.1.2
eth-tester==0.1.0b27
eth-utils==1.0.3
ethereum==1.6.1
Flask==1.0.2
Flask-GraphQL==1.4.1
graphene==2.1
graphene-django==2.0.0
graphql-core==2.0
graphql-relay==0.4.5
hexbytes==0.1.0
idna==2.7
iso8601==0.1.12
itsdangerous==0.24
Jinja2==2.10
kombu==4.2.1
lru-dict==1.1.6
MarkupSafe==1.0
parsimonious==0.8.0
pbkdf2==1.3
promise==2.1
psycopg2-binary==2.7.5
py-solc==3.1.0
pycparser==2.18
pycryptodome==3.6.1
pyethash==0.1.27
PyGithub==1.40
PyJWT==1.6.4
pysha3==1.0.2
pytz==2018.5
PyYAML==3.12
redis==2.10.6
repoze.lru==0.7
requests==2.19.1
rlp==0.6.0
Rx==1.6.1
scrypt==0.8.6
secp256k1==0.13.2
semantic-version==2.6.0
singledispatch==3.4.0.3
six==1.11.0
SQLAlchemy==1.2.9
toolz==0.9.0
typing==3.6.4
urllib3==1.23
vine==1.1.4
web3==4.3.0
websockets==4.0.1
Werkzeug==0.14.1
django-cors-headers==2.3.0
```

Upgrading to using `py-evm` meant upgrading `rlp` and uninstalling `ethereum`. 

The offending line of code is https://github.com/ethereum/py-evm/blob/931e91531389c1a5f26f8f0690d04a7bca65e24a/eth/validation.py#L108 which says that `str`-like addresses need to have a length of 20 - this seems wrong to me but I'm still quite new to the world of ethereum.

**Comment by pipermerriam** [comment]
Haven't dug in yet, but something is leaking through and not getting properly normalized.

**Comment by pipermerriam** [comment]
The error is that you are using the `PyEVMBackend` directly without wrapping it the the `EthereumTester` class.

```
# wrong
W3 = Web3(EthereumTesterProvider(PyEVMBackend()))

# correct
from eth_tester import EthereumTester
W3 = Web3(EthereumTesterProvider(EthereumTester(PyEVMBackend()))
```

**Comment by paymog** [comment]
@pipermerriam that worked! Any chance you might know why I'm getting this error message now? `evm.exceptions.OutOfGas: Out of gas: Needed 2743200 - Remaining 1819529 - Reason: Write contract code for CREATE` considering I'm using the `EthereumTesterProvider`? It seems I *need* to specify `'gas': 3000000` in the transaction dictionary `transaction={'from': w3.eth.accounts[0], 'gas': 3000000}`. Is there a way around this during testing?

**Comment by pipermerriam** [comment]
Consider opening a second issue. Not enough detail here for me to diagnose.
