### ISSUE TITLE
FastChainSyncer._load_and_process_headers() crashed and failed to be restarted

### ISSUE THREAD

**Issue by gsalgado** [ethereum/py-evm#1250]
`FastChainSyncer._load_and_process_headers()` crashed and failed to be restarted, causing trinity to continue running but not syncing

```
    INFO  09-04 15:59:10        peer  Adding ETHPeer <Node(0xbbb3@81.169.153.213)> to pool
    INFO  09-04 15:59:10       chain  Starting sync with ETHPeer <Node(0xbbb3@81.169.153.213)>
    INFO  09-04 15:59:18        peer  ETHPeer <Node(0x94c1@192.81.208.223)> finished, removing from pool
    INFO  09-04 15:59:27       chain  Imported 167 blocks (3222 txs) in 15.37 seconds, new head: #3837178
   ERROR  09-04 15:59:43       chain  Unknown error when getting block bodies
Traceback (most recent call last):
  File "/home/salgado/src/py-evm/trinity/sync/full/chain.py", line 213, in _get_block_bodies
    block_body_bundles = await peer.requests.get_block_bodies(batch)
  File "/home/salgado/src/py-evm/trinity/protocol/eth/exchanges.py", line 156, in __call__
    timeout,
  File "/home/salgado/src/py-evm/trinity/protocol/common/exchanges.py", line 72, in get_result
    await self._manager.launch_service()
  File "/home/salgado/src/py-evm/trinity/protocol/common/managers.py", line 209, in launch_service
    self._peer.run_daemon(self._response_stream)
  File "/home/salgado/src/py-evm/p2p/service.py", line 173, in run_daemon
    f"Can't restart daemon {service!r}, child of {self!r}: it's already completed"
eth_utils.exceptions.ValidationError: Can't restart daemon <ResponseCandidateStream(ETHPeer <Node(0xbbb3@81.169.153.213)>, <class 'trinity.protocol.eth.commands.BlockBodies'>)>, child of ETHPeer <Node(0xbbb3ad8be9684fa1d67ac057d18f7357dd236dc01a806fef6977ac9a259b352c00169d092c50475b80aed9e28eff12d2038e97971e0be3b934b366e86b59a723@81.169.153.213:30303)>: it's already completed
    INFO  09-04 15:59:43        peer  ETHPeer <Node(0xbbb3@81.169.153.213)> finished, removing from pool
 WARNING  09-04 15:59:43     service  Task <coroutine object FastChainSyncer._load_and_process_headers at 0x7f25e0f78938> finished unexpectedly: No connected peers have the block bodies we need for td=9288694621430187
    INFO  09-04 15:59:43   discovery  Invariant: received ping from this_node: <Node(0x0b2c@127.0.0.1)>
    INFO  09-04 15:59:56        peer  Connected peers: 0 inbound, 0 outbound
    INFO  09-04 15:59:56        peer  Peer subscribers: 1, longest queue: FastChainSyncer(0)
```

**Comment by carver** [comment]
Pretty sure this was fixed by https://github.com/ethereum/py-evm/pull/1249/files#diff-31d44fca310c7755ffc8e946f659e7c3R204
