### ISSUE TITLE
DecryptionError escaping

### ISSUE THREAD

**Issue by cburgdorf** [ethereum/py-evm#1298]
### What is wrong?

```
 <Node(0xaa36fdf33dd030378a0168efe6ed7d5cc587fafa3cdd375854fe735a2e11ea3650ba29644e2db48368c46e1f60e716300ba49396cd63778bf8a818c09bded46f@13.93.211.84:30303)>, <Node(0x78de8a0916848093c73790ead81d1928bec737d565119932b98c6b100d944b7a95e94f847f689fc723399d2e31129d182f7ef3863f2b4c820abbf3ab2722344d@191.235.84.50:30303)>, <Node(0x158f8aab45f6d19c6cbf4a089c2670541a8da11978a2f90dbf6a502a4a3bab80d288afdbeb7ec0ef6d92de563767f3b1ea9e8e334ca711e9f8e2df5a0385e8e6@13.75.154.138:30303)>, <Node(0x1118980bf48b0a3640bdba04e0fe78b1add18e1cd99bf22d53daac1fd9972ad650df52176e7c7d89d1114cfef2bc23a2959aa54998a46afcf7d91809f0855082@52.74.57.123:30303)>)\n'
b'    INFO  09-13 21:24:44     service  Starting fast-sync; current head: #0\n'
b'   ERROR  09-13 21:24:51        peer  Unexpected error during auth/p2p handshake with <Node(0x4aaef89859ce7474eb3f3601b2118d7f376029e0261135c9bcb2ab6371e3c47e53001976cffa43587ef5d6021667443f047be0736989042523ec13c5f1eabe42@47.100.184.138:30303)>\n'
b'Traceback (most recent call last):\n'
b'  File "/home/circleci/repo/p2p/peer.py", line 919, in connect\n'
b'    self.cancel_token))\n'
b'  File "/home/circleci/repo/p2p/cancellable.py", line 19, in wait\n'
b'    return await self.wait_first(awaitable, token=token, timeout=timeout)\n'
b'  File "/home/circleci/repo/p2p/cancellable.py", line 41, in wait_first\n'
b'    return await token_chain.cancellable_wait(*awaitables, timeout=timeout)\n'
b'  File "/home/circleci/repo/.tox/py36-trinity-integration/lib/python3.6/site-packages/cancel_token/token.py", line 152, in cancellable_wait\n'
b'    return done.pop().result()\n'
b'  File "/home/circleci/repo/p2p/peer.py", line 160, in handshake\n'
b'    await peer.do_p2p_handshake()\n'
b'  File "/home/circleci/repo/p2p/peer.py", line 283, in do_p2p_handshake\n'
b'    cmd, msg = await self.read_msg()\n'
b'  File "/home/circleci/repo/p2p/peer.py", line 471, in read_msg\n'
b'    msg = self.decrypt_body(frame_data, frame_size)\n'
b'  File "/home/circleci/repo/p2p/peer.py", line 600, in decrypt_body\n'
b"    f'Invalid frame mac: expected {expected_frame_mac}, got {frame_mac}'\n"
b"p2p.exceptions.DecryptionError: Invalid frame mac: expected b'\\xde\\xcag\\x0e\\x94\\xdbkC\\xa8\\xc4\\xb8\\x10\\xdb@\\xf8o', got b'\\xdd\\x16\\xcea]B\\xbd1\\x8a\\x0f\\xa7\\xe8B\\x87\\xf9\\xce'\n"
```

https://circleci.com/gh/ethereum/py-evm/77685?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

### How can it be fixed

:hear_no_evil:

**Comment by pipermerriam** [comment]
Look like this could be handled in `BasePeer.read_msg`.  The calls to both `decrypt_body` and `decrypt_header` could be wrapped in `try/except`, converting the `DecryptionError` to a `MalformedMessage`.

**Comment by Bhargavasomu** [comment]
I would like to work on this issue. Could you please help me by giving some guidance on where to start in the codebase?

**Comment by pipermerriam** [comment]
@Bhargavasomu my previous comment should include sufficient information to start on this issue.

**Comment by Bhargavasomu** [comment]
@pipermerriam @cburgdorf I have made the necessary changes and the error is not coming. All the test cases except py36-lint passed. I am not able to figure out why py36-lint failed. Could you please guide me?

**Comment by hwwhww** [comment]
@Bhargavasomu 
```
/home/circleci/repo/p2p/peer.py:391:101: E501 line too long (102 > 100 characters)
/home/circleci/repo/p2p/peer.py:399:101: E501 line too long (101 > 100 characters)
/home/circleci/repo/p2p/peer.py:400:101: E501 line too long (101 > 100 characters)
```

Some typesetting / making that into more lines should fix the py36-lint errors.

**Comment by Bhargavasomu** [comment]
@pipermerriam was detecting the DecryptionError as part of the issue? Because I thought you mentioned "converting the DecryptionError to a MalformedMessage"

**Comment by Bhargavasomu** [comment]
@pipermerriam I have made the necessary changes. Please let me know the changes needed if any

**Comment by Bhargavasomu** [comment]
@pipermerriam is the PR ok for merging or still anything else needs to be done?
