### ISSUE TITLE
Invalid argument warning for coroutine object BaseBodyChainSyncer._run_body_download_batch

### ISSUE THREAD

**Issue by MysticRyuujin** [ethereum/py-evm#1387]
`0.1.0a16/linux/cpython3.6.6`

### What is wrong?

```
    INFO  10-11 16:50:51        FullNodeSyncer  Starting fast-sync; current head: #4145407
    INFO  10-11 16:50:51           ETHPeerPool  Adding ETHPeer <Node(0x35b3@192.168.15.33)> to pool
    INFO  10-11 16:50:51       FastChainSyncer  Starting sync with ETHPeer <Node(0x35b3@192.168.15.33)>
    INFO  10-11 16:50:52           ETHPeerPool  ETHPeer <Node(0x35b3@192.168.15.33)> finished, removing from pool
    INFO  10-11 16:50:53       FastChainSyncer  ETHPeer <Node(0x35b3@192.168.15.33)> disconnected, aborting sync
    INFO  10-11 16:50:55           ETHPeerPool  Adding ETHPeer <Node(0x865a@52.176.100.77)> to pool
    INFO  10-11 16:50:55       FastChainSyncer  Starting sync with ETHPeer <Node(0x865a@52.176.100.77)>
 WARNING  10-11 16:50:58               ETHPeer  Task <coroutine object BaseBodyChainSyncer._run_body_download_batch at 0x7fc854536f10> finished unexpectedly: b'IO error: /root/.local/share/trinity/ropsten/chain/full/2468589.ldb: Invalid argument'
 WARNING  10-11 16:50:59               ETHPeer  Task <coroutine object FastChainSyncer._run_receipt_download_batch at 0x7fc85451a0f8> finished unexpectedly: b'IO error: /root/.local/share/trinity/ropsten/chain/full/2468589.ldb: Invalid argument'
    INFO  10-11 16:51:51           ETHPeerPool  Connected peers: 0 inbound, 1 outbound
    INFO  10-11 16:51:51           ETHPeerPool  Peer subscribers: 1, longest queue: FastChainSyncer(0)
    INFO  10-11 16:52:51           ETHPeerPool  Connected peers: 0 inbound, 1 outbound
    INFO  10-11 16:52:51           ETHPeerPool  Peer subscribers: 1, longest queue: FastChainSyncer(0)
    INFO  10-11 16:53:51           ETHPeerPool  Connected peers: 0 inbound, 1 outbound
    INFO  10-11 16:53:51           ETHPeerPool  Peer subscribers: 1, longest queue: FastChainSyncer(0)
    INFO  10-11 16:54:48           ETHPeerPool  Adding ETHPeer <Node(0x35b3@192.168.15.33)> to pool
 WARNING  10-11 16:54:51               ETHPeer  Task <coroutine object BaseBodyChainSyncer._run_body_download_batch at 0x7fc854568938> finished unexpectedly: b'IO error: /root/.local/share/trinity/ropsten/chain/full/2468589.ldb: Invalid argument'
    INFO  10-11 16:54:51           ETHPeerPool  Connected peers: 0 inbound, 2 outbound
    INFO  10-11 16:54:51           ETHPeerPool  Peer subscribers: 1, longest queue: FastChainSyncer(0)
 WARNING  10-11 16:54:53               ETHPeer  Task <coroutine object FastChainSyncer._run_receipt_download_batch at 0x7fc854492f68> finished unexpectedly: b'IO error: /root/.local/share/trinity/ropsten/chain/full/2468589.ldb: Invalid argument'
    INFO  10-11 16:55:28           ETHPeerPool  ETHPeer <Node(0x865a@52.176.100.77)> finished, removing from pool
    INFO  10-11 16:55:51           ETHPeerPool  Connected peers: 0 inbound, 1 outbound
    INFO  10-11 16:55:51           ETHPeerPool  Peer subscribers: 1, longest queue: FastChainSyncer(0)
    INFO  10-11 16:56:51           ETHPeerPool  Connected peers: 0 inbound, 1 outbound
    INFO  10-11 16:56:51           ETHPeerPool  Peer subscribers: 1, longest queue: FastChainSyncer(0)
```

**Comment by pipermerriam** [comment]
Can you provide us with the debug log output.  It should be located in `$HOME/.local/share/trinity/mainnet/logs/trinity.log` or somewhere near that location if you are running ropsten or a light client.

**Comment by MysticRyuujin** [comment]
Sure! Here you go!

[trinity.zip](https://github.com/ethereum/py-evm/files/2470617/trinity.zip)

**Comment by pipermerriam** [comment]
It looks like your logs rolled over, initial timestamp on that log is `10-11 18:46.12`.  If you look in that directory you should see additional logfiles, can you find the one that contains the timestamps above, you should be able to do this with a quick grep of one of the timestamps.

**Comment by MysticRyuujin** [comment]
Sure, here you go. I figured since the logs contained the same error it wouldn't matter but I think this is it.

[trinity.log.3.zip](https://github.com/ethereum/py-evm/files/2473784/trinity.log.3.zip)

**Comment by pipermerriam** [comment]
Sorry, I didn't actually look for the error in those logs, thanks for your patience.

**Comment by pipermerriam** [comment]
relevant section:

```
230633  WARNING  10-11 16:50:58               ETHPeer  Task <coroutine object BaseBodyChainSyncer._run_body_download_batch at 0x7fc854536f10>
       finished unexpectedly: b'IO error: /root/.local/share/trinity/ropsten/chain/full/2468589.ldb: Invalid argument'
230634    DEBUG  10-11 16:50:58               ETHPeer  Task failure traceback
230635 trinity.chains.RemoteTraceback:
230636 """
230637 Traceback (most recent call last):
230638   File "/usr/local/lib/python3.6/dist-packages/trinity/chains/__init__.py", line 184, in wrapper
230639     return attr(*args, **kwargs)
230640   File "/usr/local/lib/python3.6/dist-packages/eth/db/chain.py", line 473, in persist_trie_data_dict
230641     db[key] = value
230642   File "/usr/lib/python3.6/contextlib.py", line 88, in __exit__
230643     next(self.gen)
230644   File "/usr/local/lib/python3.6/dist-packages/eth/db/backends/level.py", line 62, in atomic_batch
230645     readable_batch.decommission()
230646   File "plyvel/_plyvel.pyx", line 634, in plyvel._plyvel.WriteBatch.__exit__
230647   File "plyvel/_plyvel.pyx", line 617, in plyvel._plyvel.WriteBatch.write
230648   File "plyvel/_plyvel.pyx", line 88, in plyvel._plyvel.raise_for_status
230649 plyvel._plyvel.IOError: b'IO error: /root/.local/share/trinity/ropsten/chain/full/2468589.ldb: Invalid argument'
230650 """
230651
230652 The above exception was the direct cause of the following exception:
230653
230654 Traceback (most recent call last):
230655   File "/usr/local/lib/python3.6/dist-packages/p2p/service.py", line 136, in _run_task_wrapper
230656     await awaitable
230657   File "/usr/local/lib/python3.6/dist-packages/trinity/sync/full/chain.py", line 223, in _run_body_download_batch
230658     await self._block_body_bundle_processing(bundles)
230659   File "/usr/local/lib/python3.6/dist-packages/trinity/sync/full/chain.py", line 636, in _block_body_bundle_processing
230660     await self.wait(self.db.coro_persist_trie_data_dict(trie_data_dict))
230661   File "/usr/local/lib/python3.6/dist-packages/p2p/cancellable.py", line 19, in wait
230662     return await self.wait_first(awaitable, token=token, timeout=timeout)
230663   File "/usr/local/lib/python3.6/dist-packages/p2p/cancellable.py", line 41, in wait_first
230664     return await token_chain.cancellable_wait(*awaitables, timeout=timeout)
230665   File "/usr/local/lib/python3.6/dist-packages/cancel_token/token.py", line 152, in cancellable_wait
230666     return done.pop().result()
230667   File "/usr/local/lib/python3.6/dist-packages/trinity/utils/mp.py", line 27, in method
230668     args,
230669   File "/usr/lib/python3.6/concurrent/futures/thread.py", line 56, in run
230670     result = self.fn(*self.args, **self.kwargs)
230671   File "/usr/lib/python3.6/multiprocessing/managers.py", line 772, in _callmethod
230672     raise convert_to_error(kind, result)
230673 plyvel._plyvel.IOError: b'IO error: /root/.local/share/trinity/ropsten/chain/full/2468589.ldb: Invalid argument'
```

**Comment by pipermerriam** [comment]
Looks like it could be this: https://github.com/google/leveldb/issues/281

**Comment by pipermerriam** [comment]
This one seems more informative: https://github.com/Level/levelup/issues/222

**Comment by MysticRyuujin** [comment]
The Ubuntu system it's running on is a VMWare Workstation VM, but Trinity is running directly on that VM
