### ISSUE TITLE
Fix escaped exception during peer connecting

### ISSUE THREAD

**Issue by cburgdorf** [ethereum/py-evm#1453]
### What is wrong?

This exception escapes during regular mode syncing.

```
   ERROR  11-08 15:54:11     service  Unexpected error in <p2p.discovery.DiscoveryService object at 0x7fe6b183bfd0>, exiting
Traceback (most recent call last):
  File "/home/ubuntu/py-evm/venv/lib/python3.6/site-packages/p2p/service.py", line 60, in run
    await self._run()
  File "/home/ubuntu/py-evm/venv/lib/python3.6/site-packages/p2p/discovery.py", line 339, in _run
    await self.maybe_connect_to_more_peers()
  File "/home/ubuntu/py-evm/venv/lib/python3.6/site-packages/p2p/discovery.py", line 351, in maybe_connect_to_more_peers
    self.proto.get_nodes_to_connect(self.peer_pool.max_peers))
  File "/home/ubuntu/py-evm/venv/lib/python3.6/site-packages/p2p/peer.py", line 817, in connect_to_nodes
    await self.start_peer(peer)
  File "/home/ubuntu/py-evm/venv/lib/python3.6/site-packages/p2p/peer.py", line 732, in start_peer
    msgs = await self.ensure_same_side_on_dao_fork(peer)
  File "/home/ubuntu/py-evm/venv/lib/python3.6/site-packages/p2p/peer.py", line 847, in ensure_same_side_on_dao_fork
    peer.read_msg(), timeout=remaining_timeout)
  File "/home/ubuntu/py-evm/venv/lib/python3.6/site-packages/p2p/cancel_token.py", line 102, in wait
    return await self.wait_first(awaitable, token=token, timeout=timeout)
  File "/home/ubuntu/py-evm/venv/lib/python3.6/site-packages/p2p/cancel_token.py", line 124, in wait_first
    return await wait_with_token(*awaitables, token=token_chain, timeout=timeout)
  File "/home/ubuntu/py-evm/venv/lib/python3.6/site-packages/p2p/cancel_token.py", line 161, in wait_with_token
    return done.pop().result()
  File "/home/ubuntu/py-evm/venv/lib/python3.6/site-packages/p2p/peer.py", line 348, in read_msg
    decoded_msg = cast(Dict[str, Any], cmd.decode(msg))
  File "/home/ubuntu/py-evm/venv/lib/python3.6/site-packages/p2p/protocol.py", line 97, in decode
    return self.decode_payload(data[1:])
  File "/home/ubuntu/py-evm/venv/lib/python3.6/site-packages/p2p/protocol.py", line 84, in decode_payload
    data = rlp.decode(rlp_data, sedes=decoder)
  File "/home/ubuntu/py-evm/venv/lib/python3.6/site-packages/rlp/codec.py", line 228, in decode
    item, per_item_rlp, end = consume_item(rlp, 0)
  File "/home/ubuntu/py-evm/venv/lib/python3.6/site-packages/rlp/codec.py", line 204, in consume_item
    return consume_payload(rlp, p, s, t, l)
  File "/home/ubuntu/py-evm/venv/lib/python3.6/site-packages/rlp/codec.py", line 179, in consume_payload
    item, item_rlp, next_item_start = consume_payload(rlp, p, s, t, l)
  File "/home/ubuntu/py-evm/venv/lib/python3.6/site-packages/rlp/codec.py", line 179, in consume_payload
    item, item_rlp, next_item_start = consume_payload(rlp, p, s, t, l)
  File "/home/ubuntu/py-evm/venv/lib/python3.6/site-packages/rlp/codec.py", line 178, in consume_payload
    p, t, l, s = consume_length_prefix(rlp, next_item_start)
  File "/home/ubuntu/py-evm/venv/lib/python3.6/site-packages/rlp/codec.py", line 132, in consume_length_prefix
    raise DecodingError('Encoded as short string although single byte was possible', rlp)
rlp.exceptions.DecodingError: Encoded as short string although single byte was possible

```

### How can it be fixed

:see_no_evil: :hear_no_evil:

**Comment by cburgdorf** [comment]
Ok, there's something weird about this. The code doesn't seem to match latest master. Investigating.

**Comment by cburgdorf** [comment]
Ok, the box where this error comes from does not run on latest master. Closing.
