### ISSUE TITLE
Cannot run Trinity: ContextualVersionConflict and Cryptography DistributionNotFound

### ISSUE THREAD

**Issue by glaksmono** [ethereum/py-evm#1477]
* py-evm Version: `master`
* OS: MacOS Mojave 10.14.1 
* Python Version (python --version): Python 3.6.4
* Environment (output of `pip freeze`): 

```
(venv) ➜  py-evm git:(py-evm-1466) ✗ pip freeze
alabaster==0.7.12
apipkg==1.5
appnope==0.1.0
argh==0.26.2
asn1crypto==0.24.0
async-generator==1.10
async-lru==0.1.0
asyncio-cancel-token==0.1.0a2
atomicwrites==1.2.1
attrdict==2.0.0
attrs==18.2.0
Babel==2.6.0
backcall==0.1.0
bleach==3.0.2
bloom-filter==1.3
bumpversion==0.5.3
cachetools==2.1.0
certifi==2018.10.15
cffi==1.11.5
chardet==3.0.4
coincurve==8.0.2
colorama==0.4.0
coverage==4.5.2
cryptography==2.4.1
cytoolz==0.9.0.1
decorator==4.3.0
docopt==0.6.2
docutils==0.14
eth-abi==1.2.2
eth-account==0.2.3
eth-bloom==1.0.1
eth-hash==0.2.0
eth-keyfile==0.5.1
eth-keys==0.2.0b3
eth-rlp==0.1.2
eth-typing==2.0.0
eth-utils==1.3.0
execnet==1.5.0
flake8==3.5.0
hexbytes==0.1.0
hypothesis==3.69.5
idna==2.7
ifaddr==0.1.4
imagesize==1.1.0
ipaddress==1.0.22
ipython==6.5.0
ipython-genutils==0.2.0
jedi==0.13.1
Jinja2==2.10
lahja==0.9.0
lru-dict==1.1.6
lxml==4.2.5
MarkupSafe==1.1.0
mccabe==0.6.1
more-itertools==4.3.0
mypy==0.641
mypy-extensions==0.4.1
netdisco==2.2.0
netifaces==0.10.7
packaging==18.0
parsimonious==0.8.1
parso==0.3.1
pathtools==0.1.2
pexpect==4.6.0
pickleshare==0.7.5
pkginfo==1.4.2
pluggy==0.8.0
plyvel==1.0.5
prompt-toolkit==1.0.15
ptyprocess==0.6.0
py==1.7.0
py-ecc==1.4.3
-e git+git@github.com:glaksmono/py-evm.git@1f60fd8576d4959c7d4642f52ac56158658cc9ae#egg=py_evm
pycodestyle==2.3.1
pycparser==2.19
pycryptodome==3.7.0
pyethash==0.1.27
pyflakes==1.6.0
Pygments==2.2.0
pyparsing==2.3.0
pysha3==1.0.2
pytest==4.0.0
pytest-asyncio==0.9.0
pytest-asyncio-network-simulator==0.1.0a2
pytest-cov==2.5.1
pytest-watch==4.2.0
pytest-xdist==1.18.1
python-dateutil==2.7.5
pytz==2018.7
PyYAML==3.13
readme-renderer==24.0
requests==2.20.1
requests-toolbelt==0.8.0
rlp==1.0.3
simplegeneric==0.8.1
six==1.11.0
snowballstemmer==1.2.1
Sphinx==1.7.9
sphinx-rtd-theme==0.4.2
sphinxcontrib-asyncio==0.2.0
sphinxcontrib-websupport==1.1.0
termcolor==1.1.0
toolz==0.9.0
tox==2.7.0
tqdm==4.28.1
traitlets==4.3.2
trie==1.3.8
twine==1.12.1
typed-ast==1.1.0
uPnPClient==0.0.8
urllib3==1.24.1
uvloop==0.11.2
virtualenv==16.1.0
watchdog==0.9.0
wcwidth==0.1.7
web3==4.4.1
webencodings==0.5.1
websockets==5.0.1
zeroconf==0.21.3
````

### What is wrong?

Cannot run `trinity`
```
(venv) ➜  py-evm git:(py-evm-1466) ✗ trinity
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pkg_resources/__init__.py", line 659, in _build_master
    ws.require(__requires__)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pkg_resources/__init__.py", line 967, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pkg_resources/__init__.py", line 858, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (rlp 0.6.0 (/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages), Requirement.parse('rlp<2.0.0,>=1.0.3'), {'py-evm'})

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/bin/trinity", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3017, in <module>
    @_call_aside
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3003, in _call_aside
    f(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3030, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pkg_resources/__init__.py", line 661, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pkg_resources/__init__.py", line 674, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pkg_resources/__init__.py", line 853, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'cryptography<3.0.0,>=2.0.3' distribution was not found and is required by py-evm
```

**Comment by veox** [comment]
> py-evm Version: `master`

What's `git describe --tags` give? `trinity-v0.1.0-alpha.16-194-g1f60fd85`?

**Comment by glaksmono** [comment]
@veox I'm getting this `v0.2.0-alpha.17-1005-g1f60fd85`

**Comment by veox** [comment]
Same commit on my Arch Linux box, using Python 3.7.0 and `pip` 18.0, and I'm not getting this error.

Suggests the issue either being Mac-specific, or your particular setup.

The exception message looks like it's trying to use some other environment. Do you have `rlp==0.6.0` installed anywhere else, e.g. system-wide or for the user?..

Have you tried upgrading the packages in the virtual environment?

Have you tried a "clean room" install, i.e. re-creating the venv from scratch?

**Comment by glaksmono** [comment]
Do `pip freeze` outside of the `venv` and I found that somehow there's `py-evm` installed. I did `pip uninstall py-evm` and now `trinity` works ok

Wasn't to sure when / why I did `pip install py-evm` though
