### ISSUE TITLE
Too many open files durin state sync

### ISSUE THREAD

**Issue by cburgdorf** [ethereum/py-evm#1479]
### What is wrong?

After some time (days) the state sync stalls and log is full of these:

```
DEBUG  11-18 20:55:36       StateDownloader  Task failure traceback
Traceback (most recent call last):
  File "/home/ubuntu/py-evm/p2p/service.py", line 141, in _run_task_wrapper
    await awaitable
  File "/home/ubuntu/py-evm/trinity/sync/full/state.py", line 218, in _request_and_process_nodes
    await self._process_nodes(node_data)
  File "/home/ubuntu/py-evm/trinity/sync/full/state.py", line 134, in _process_nodes
    await self.scheduler.process([(node_key, node)])
  File "/home/ubuntu/py-evm/trinity/sync/full/hexary_trie.py", line 227, in process
    await self.commit(request)
  File "/home/ubuntu/py-evm/trinity/sync/full/hexary_trie.py", line 237, in commit
    self.nodes_cache[request.node_key] = b''
  File "/home/ubuntu/py-evm/eth/db/backends/level.py", line 51, in __setitem__
    self.db.put(key, value)
  File "plyvel/_plyvel.pyx", line 331, in plyvel._plyvel.DB.put
  File "plyvel/_plyvel.pyx", line 88, in plyvel._plyvel.raise_for_status
plyvel._plyvel.IOError: b'IO error: /tmp/pyevm-state-sync-cachehygvcf44/006748.ldb: Too many open files'
 WARNING  11-18 20:55:36       StateDownloader  Task <coroutine object StateDownloader._request_and_process_nodes at 0x7f9011ec6b48> finished unexpectedly: b'IO error: /tmp/pyevm-state-sync-cachehygvcf44/006748.ldb: Too many open files'

```

This was reported before: https://github.com/ethereum/py-evm/issues/524

### How can it be fixed

:see_no_evil: :hear_no_evil:

**Comment by pipermerriam** [comment]
I suspect we may have to tweak our leveldb settings.

https://plyvel.readthedocs.io/en/latest/api.html#DB

I'd go look at the settings go-ethereum is using for it's database.

**Comment by cburgdorf** [comment]
Correct! I just looked briefly into this (because it's the end of my working day) but if anyone wants to take a stab at it, Here's what I believe geth does:

1. Figure out the max open file supported by the OS per process

2. Reserve half of them for LevelDB https://github.com/holiman/go-ethereum/blob/ec28a58cc1cc1671a09061d5aa24d1c4c9c77b9f/cmd/utils/flags.go#L716-L730

3. Pass that to level db on init https://github.com/ethereum/go-ethereum/blob/d31f1f4fdb905acb3d7c766683e584bb17f8df0d/ethdb/database.go#L77

Notice that `OpenFilesCacheCapacity` is essentially  `MaxOpenFiles`

https://gitter.im/ethereum/go-ethereum?at=5547e9e1dfe856bc1179d8c7
