### ISSUE TITLE
Regular sync throws exception

### ISSUE THREAD

**Issue by cburgdorf** [ethereum/py-evm#1494]
### What is wrong?

I wanted to force a regular sync (so I slightly modified the code to do that until we have #1480). 

I ran into the following exception which I believe is a regression from when we introduced atomic writes.

```
 WARNING  11-21 17:36:26    RegularChainSyncer  Task <coroutine object RegularChainSyncer._import_ready_blocks at 0x7f6262706780> finished unexpectedly: 'DBProxy' object has no attribute 'atomic_batch'
```

### How can it be fixed

Probably need to expose `atomic_batch` on the `DBProxy`

**Comment by cburgdorf** [comment]
This is looking to be problematic. Just exposing `atomic_batch` on the `DBProxy` doesn't seem to work.

```
 WARNING  11-21 18:02:45    RegularChainSyncer  Task <coroutine object RegularChainSyncer._import_ready_blocks at 0x7ff7d7282728> finished unexpectedly: 
---------------------------------------------------------------------------
Unserializable message: Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/managers.py", line 283, in serve_client
    send(msg)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 206, in send
    self._send_bytes(_ForkingPickler.dumps(obj))
  File "/usr/lib/python3.6/multiprocessing/reduction.py", line 51, in dumps
    cls(buf, protocol).dump(obj)
TypeError: can't pickle generator objects
```

:sob:

**Comment by pipermerriam** [comment]
@cburgdorf I think atomic batch has to be implemented on the client side of the two processes, wrapping the proxy DB such that it knows how to do the atomic batching locally.
