### ISSUE TITLE
Installation of external plugins broken

### ISSUE THREAD

**Issue by cburgdorf** [ethereum/py-evm#1547]
### What is wrong?

```
$ pip install ./trinity-external-plugins/examples/peer_count_reporter/
Processing ./trinity-external-plugins/examples/peer_count_reporter
Building wheels for collected packages: trinity-peer-count-reporter-plugin
  Running setup.py bdist_wheel for trinity-peer-count-reporter-plugin ... done
  Stored in directory: /tmp/pip-ephem-wheel-cache-4feh3p99/wheels/81/fb/9e/ab0d1ff12d1589a26e07fef18a6481ab4abcf7e888f0a5f9ad
Successfully built trinity-peer-count-reporter-plugin
Installing collected packages: trinity-peer-count-reporter-plugin
Successfully installed trinity-peer-count-reporter-plugin-0.0.0
(venv) cburgdorf at craftbot in ~/Documents/hacking/ef/py-evm2 on master
$ trinity --help
Traceback (most recent call last):
  File "/home/cburgdorf/Documents/hacking/ef/py-evm2/venv/bin/trinity", line 11, in <module>
    load_entry_point('py-evm', 'console_scripts', 'trinity')()
  File "/home/cburgdorf/Documents/hacking/ef/py-evm2/trinity/main.py", line 115, in main
    MainAndIsolatedProcessScope(event_bus, main_endpoint)
  File "/home/cburgdorf/Documents/hacking/ef/py-evm2/trinity/main.py", line 380, in setup_plugins
    plugin_manager.register(get_all_plugins())
  File "/home/cburgdorf/Documents/hacking/ef/py-evm2/trinity/plugins/registry.py", line 58, in get_all_plugins
    return BUILTIN_PLUGINS + discover_plugins()
  File "/home/cburgdorf/Documents/hacking/ef/py-evm2/trinity/plugins/registry.py", line 53, in discover_plugins
    entry_point.load()() for entry_point in pkg_resources.iter_entry_points('trinity.plugins')
  File "/home/cburgdorf/Documents/hacking/ef/py-evm2/trinity/plugins/registry.py", line 53, in <genexpr>
    entry_point.load()() for entry_point in pkg_resources.iter_entry_points('trinity.plugins')
  File "/home/cburgdorf/Documents/hacking/ef/py-evm2/venv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2346, in load
    return self.resolve()
  File "/home/cburgdorf/Documents/hacking/ef/py-evm2/venv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2352, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
ModuleNotFoundError: No module named 'peer_count_reporter_plugin'

```
### How can it be fixed

Fill this in if you know how to fix it.

**Comment by cburgdorf** [comment]
Ok, turns out, this works as expected when `pip install` uses the `-e` flag.

E.g `pip install -e ./trinity-external-plugins/examples/peer_count_reporter/`

Maybe this is because we are installing it from a local directory? If we would install an external plugin directly through pypi I would assume that it would also work without the `-e` option but that's just a blind guess.

I'm closing this for now as I believe this is just a `pip` thing.
