### ISSUE TITLE
Event bus raises CancelledError during shutdown

### ISSUE THREAD

**Issue by carver** [ethereum/py-evm#1561]
lajha: 0.9.0

### What is wrong?

During shutdown, got:
```
 WARNING  12-07 15:41:19              FullNode  Task <coroutine object Node.handle_network_id_requests at 0x7f1f44bf87d8> finished unexpectedly:
   DEBUG  12-07 15:41:19              FullNode  Task failure traceback
Traceback (most recent call last):
  File "/home/jcarver/code/py-evm/p2p/service.py", line 141, in _run_task_wrapper
    await awaitable
  File "/home/jcarver/code/py-evm/p2p/service.py", line 160, in _run_daemon_task_wrapper
    await awaitable
  File "/home/jcarver/code/py-evm/trinity/nodes/base.py", line 60, in handle_network_id_requests
    async for req in self.event_bus.stream(NetworkIdRequest):
  File "/home/jcarver/code/py-evm/venv/lib/python3.6/site-packages/lahja/endpoint.py", line 267, in stream
    raise e
  File "/home/jcarver/code/py-evm/venv/lib/python3.6/site-packages/lahja/endpoint.py", line 261, in stream
    yield await queue.get()
  File "/usr/lib/python3.6/asyncio/queues.py", line 167, in get
    yield from getter
concurrent.futures._base.CancelledError
```
### How can it be fixed

Maybe use the new `self.wait_iter` so the iteration dies when the service is cancelled.

**Comment by cburgdorf** [comment]
Ah fix for that is under way https://github.com/ethereum/lahja/pull/24
