### ISSUE TITLE
Exception from lahja escaping py-evm shutdown.

### ISSUE THREAD

**Issue by pipermerriam** [ethereum/py-evm#1613]
### What is wrong?

This is escaping during a py-evm shutdown.

```
   ERROR  12-15 15:31:54               asyncio  _GatheringFuture exception was never retrieved
future: <_GatheringFuture finished exception=InvalidStateError('invalid state',)>
Traceback (most recent call last):
  File "/home/piper/python-environments/trinity/lib/python3.6/site-packages/lahja/endpoint.py", line 123, in _connect_receiving_queue
    self._process_item(item, config)
  File "/home/piper/python-environments/trinity/lib/python3.6/site-packages/lahja/endpoint.py", line 148, in _process_item
    future.set_result(item)
asyncio.base_futures.InvalidStateError: invalid state
```

### How can it be fixed

Have not investigated.

**Comment by pipermerriam** [comment]
@cburgdorf I think this is related to the Discovery service crash.

**Comment by cburgdorf** [comment]
So, this raised when it tried to set the result for a request made through the `request` API.

https://github.com/ethereum/lahja/blob/5e3cd14815df2c279e67bba5dd78475b46741331/lahja/endpoint.py#L148

Maybe we try to set a result on a future that was already cancelled? I'm not sure if that would cause this kind of an exception but at least we do not any checks before we set the result and it may totally be that there are several things we need to check (like if the future is cancelled) before we set the result.

And the reason that the future might be cancelled is because we usually make requests with a timeout so if a response comes back late this *may* lead to situations like this. Total speculation though.

**Comment by cburgdorf** [comment]
While trying to reproduce this (no success so far) it just occurred to me that maybe we will need some locks in lahja as well. Incoming messages are received on different threads so there may be cases were locking is needed.

https://github.com/ethereum/lahja/blob/5e3cd14815df2c279e67bba5dd78475b46741331/lahja/async_util.py#L12-L24

**Comment by cburgdorf** [comment]
Ah, interesting.

>Raises a InvalidStateError error if the Future is already done.

https://docs.python.org/3/library/asyncio-future.html#asyncio.Future.set_result

This would suggest that we are trying to set the result twice. But looking at the actual implementation of `set_result` it seems it would also raise that exception if we try to set the result on an already cancelled future which seems to be a more likely case.

```python
        if self._state != _PENDING:
            raise InvalidStateError('{}: {!r}'.format(self._state, self))
```

**Comment by cburgdorf** [comment]
This *may be* a fix for it but I'm not sure.

https://github.com/ethereum/lahja/pull/26
