### ISSUE TITLE
Trinity prints noisy error message when being port-scanned in "light client" mode

### ISSUE THREAD

**Issue by veox** [ethereum/py-evm#1657]
* py-evm Version: `master` (commit 8841a6980254b93294c80a889ed3901fd6baf9c6)
* OS: Arch Linux
* Python Version (python --version): 3.7.1
* Environment (output of `pip freeze`): MISSING

### What is wrong?

Running `trinity` as

``` sh
% nice ionice -c3 trinity --network-id=1 --sync-mode=light --discv5 $ETHSTATS_OPTIONS
```

and then checking if the port is accessible with

``` sh
% nc -vz localhost 30303
```

results in this error message being printed:

``` python
   ERROR  12-20 17:58:10           LightServer  Unexpected error handling handshake
Traceback (most recent call last):
  File "/home/veox/src/py-evm/trinity/server.py", line 185, in receive_handshake
    await self._receive_handshake(reader, writer)
  File "/home/veox/src/py-evm/trinity/server.py", line 199, in _receive_handshake
    ip, socket, *_ = writer.get_extra_info("peername")
TypeError: cannot unpack non-iterable NoneType object
```

Not sure if fresh or regression.

### How can it be fixed

Not sure.

Checking how "regular" sync mode reacts to this and handles it would be a good start.

**Comment by veox** [comment]
The "fast" sync variant has:

``` python
   ERROR  12-20 18:54:08            FullServer  Unexpected error handling handshake
Traceback (most recent call last):
  File "/home/veox/src/py-evm/trinity/server.py", line 185, in receive_handshake
    await self._receive_handshake(reader, writer)
  File "/home/veox/src/py-evm/trinity/server.py", line 199, in _receive_handshake
    ip, socket, *_ = writer.get_extra_info("peername")
TypeError: cannot unpack non-iterable NoneType object
```

(Same code path.)

**Comment by pipermerriam** [comment]
So we use this API:

https://docs.python.org/3/library/asyncio-protocol.html#asyncio.BaseTransport.get_extra_info

Which delegates to this API

https://docs.python.org/3/library/socket.html#socket.socket.getpeername

It looks like we just need to implement some error handling there for the case where that returns `None` and probably log some information about the connection for debug purposes.

**Comment by veox** [comment]
@pipermerriam Works for me. ^_^ (Replied in PR.)
