### ISSUE TITLE
Corrupted Transport

### ISSUE THREAD

**Issue by pipermerriam** [ethereum/py-evm#1848]
on commit: dc9c03bfee31aecd100c953e8777988d8b296bd8 (current master)

### What is wrong?

This just blasted out of my trinity node:    

```
ERROR  09-10 19:30:02            Connection  Unexpected error in <p2p.connection.Connection object at 0x7fa0dc456940>, exiting
Traceback (most recent call last):
  File "/home/piper/projects/trinity/p2p/multiplexer.py", line 299, in multiplex
    yield
  File "/home/piper/projects/trinity/p2p/connection.py", line 82, in _run
    await self.cancellation()
  File "/home/piper/projects/trinity/p2p/service.py", line 356, in cancellation
    await self.wait(self.events.cancelled.wait())
  File "/home/piper/projects/trinity/p2p/cancellable.py", line 20, in wait
    return await self.wait_first(awaitable, token=token, timeout=timeout)
  File "/home/piper/projects/trinity/p2p/cancellable.py", line 43, in wait_first
    return await token_chain.cancellable_wait(*awaitables, timeout=timeout)
  File "/home/piper/python-environments/trinity/lib/python3.6/site-packages/cancel_token/token.py", line 176, in cancellable_wait
    "Cancellation requested by {} token".format(self.triggered_token)
cancel_token.exceptions.OperationCancelled: Cancellation requested by Connection:multiplexer[<Node(0x6b03@71.198.119.42)>]:ETHPeerPool:FullServer:FullNode token

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/piper/projects/trinity/p2p/service.py", line 118, in run
    await self._run()
  File "/home/piper/projects/trinity/p2p/connection.py", line 82, in _run
    await self.cancellation()
  File "/home/piper/python-environments/trinity/lib/python3.6/site-packages/async_generator/_util.py", line 53, in __aexit__
    await self._agen.athrow(type, value, traceback)
  File "/home/piper/projects/trinity/p2p/multiplexer.py", line 329, in multiplex
    await asyncio.wait_for(fut, timeout=1)
  File "/home/piper/.pyenv/versions/3.6.5/lib/python3.6/asyncio/tasks.py", line 358, in wait_for
    return fut.result()
  File "/home/piper/projects/trinity/p2p/multiplexer.py", line 363, in _do_multiplexing
    async for protocol, cmd, msg in msg_stream:
  File "/home/piper/projects/trinity/p2p/cancellable.py", line 67, in wait_iter
    timeout=timeout,
  File "/home/piper/projects/trinity/p2p/cancellable.py", line 20, in wait
    return await self.wait_first(awaitable, token=token, timeout=timeout)
  File "/home/piper/projects/trinity/p2p/cancellable.py", line 43, in wait_first
    return await token_chain.cancellable_wait(*awaitables, timeout=timeout)
  File "/home/piper/python-environments/trinity/lib/python3.6/site-packages/cancel_token/token.py", line 178, in cancellable_wait
    return done.pop().result()
  File "/home/piper/projects/trinity/p2p/multiplexer.py", line 57, in stream_transport_messages
    raw_msg = await transport.recv(token)
  File "/home/piper/projects/trinity/p2p/transport.py", line 258, in recv
    raise Exception(f"Corrupted transport: {self} - state={self.read_state.name}")
Exception: Corrupted transport: <p2p.transport.Transport object at 0x7fa0a87b9320> - state=BODY
```

DEBUG logs here: https://gist.github.com/pipermerriam/8d6d4e647fdedcb8ffb678ee8f8b1de3

### How can it be fixed

:question:

**Comment by pipermerriam** [comment]
wrong repo...
