### ISSUE TITLE
Update py-evm version to use for Building an app that uses Py-EVM in py-evm docs

### ISSUE THREAD

**Issue by Sabnock01** [ethereum/py-evm#2034]
* py-evm Version: 0.3.0a20
* OS: Ubuntu 20.04
* Python Version (python --version): Python 3.8.10

What is wrong?

When going through this guide https://py-evm.readthedocs.io/en/latest/guides/building_an_app_that_uses_pyevm.html running `py main.py` produces the error message: 

```
Traceback (most recent call last):   
File "app/main.py", line 36, in <module>     
chain = MainnetChain.from_genesis(AtomicDB(), GENESIS_PARAMS, GENESIS_STATE)   
File "/home/sabnock/.local/lib/python3.8/site-packages/eth/chains/base.py", line 251, in from_genesis     
genesis_header = BlockHeader(**genesis_params) 
TypeError: __init__() missing 2 required positional arguments: 'block_number' and 'gas_limit'
```

### How can it be fixed

I was able to independently rectify this by changing the evm version in `install_requires {}` to a more recent version. I get the correct output using py-evm 0.5.0a0. The documentation should be updated to suggest a more recent version of py-evm.

**Comment by fselmo** [comment]
@Sabnock01 Thanks for this! We will get an update up asap.
