### ISSUE TITLE
Getting `eth_keys.exceptions.BadSignature: Value -27 is not greater than or equal to 0` when v is `0`

### ISSUE THREAD

**Issue by pastet89** [ethereum/py-evm#2066]
* py-evm Version: `0.5.0a3`
* OS: Amazon Linux
* Python Version (python --version):  `3.9.2`
* Environment (output of `pip freeze`):
```
aiohttp==3.8.1
aiosignal==1.2.0
async-timeout==4.0.2
attrs==21.4.0
base58==2.1.1
bitarray==1.2.2
cached-property==1.5.2
certifi==2022.5.18.1
charset-normalizer==2.0.12
cytoolz==0.11.2
eth-abi==2.1.1
eth-account==0.5.7
eth-bloom==1.0.4
eth-hash==0.3.2
eth-keyfile==0.5.1
eth-keys==0.3.4
eth-rlp==0.2.1
eth-typing==2.3.0
eth-utils==1.10.0
frozenlist==1.3.0
hexbytes==0.2.2
idna==3.3
ipfshttpclient==0.8.0a2
jsonschema==4.6.0
lru-dict==1.1.7
multiaddr==0.0.9
multidict==6.0.2
mypy-extensions==0.4.3
netaddr==0.8.0
parsimonious==0.8.1
protobuf==3.20.1
py-ecc==5.2.0
py-evm==0.5.0a3
pycryptodome==3.14.1
pyethash==0.1.27
pyrsistent==0.18.1
requests==2.27.1
rlp==2.0.1
six==1.16.0
sortedcontainers==2.4.0
toolz==0.11.2
trie==2.0.0a5
typing-extensions==3.10.0.2
urllib3==1.26.9
varint==1.0.2
web3==5.29.2
websockets==9.1
yarl==1.7.2
```
### What is wrong?

I am trying to recover the sender address using the following code: 
```
def test_extract_from_account():
    w3 = web3.Web3(web3.HTTPProvider("https://eth-mainnet.alchemyapi.io/v2/XXXXXXXXXXXXXXXXXXXXXXXXXX"))
    tx = w3.eth.getTransaction("0x784fed92b7eae2853dd7a22460760613c5345ad97aff660d26c657e9f19c6a3d")
    raw_tx = recover_raw_transaction(tx)
    TransactionClass = MuirGlacierTransaction
    evm_transaction = rlp.decode(raw_tx, TransactionClass)
    sender = evm_transaction.sender
    print(sender.hex())
```

It seems to me it works well for transactions with `v` = `27` or `28`.
But when `v` of a transaction is `0x0`, I am getting: 
```
Traceback (most recent call last):
  File "/home/my_folder/py-evm/venv/lib/python3.9/site-packages/eth_keys/datatypes.py", line 380, in __init__
    self.v = v
  File "/home/my_folder/py-evm/venv/lib/python3.9/site-packages/eth_keys/datatypes.py", line 393, in v
    validate_signature_v(value)
  File "/home/my_folder/py-evm/venv/lib/python3.9/site-packages/eth_keys/validation.py", line 104, in validate_signature_v
    validate_gte(value, minimum=0)
  File "cytoolz/functoolz.pyx", line 250, in cytoolz.functoolz.curry.__call__
  File "/home/my_folder/py-evm/venv/lib/python3.9/site-packages/eth_keys/validation.py", line 30, in validate_gte
    raise ValidationError(
eth_utils.exceptions.ValidationError: Value -27 is not greater than or equal to 0

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/my_folder/py-evm/recover.py", line 68, in <module>
    print(test_extract_from_account()) ######################
  File "/home/my_folder/py-evm/recover.py", line 65, in test_extract_from_account
    sender = evm_transaction.sender
  File "/home/my_folder/py-evm/venv/lib/python3.9/site-packages/cached_property.py", line 36, in __get__
    value = obj.__dict__[self.func.__name__] = self.func(obj)
  File "/home/my_folder/py-evm/venv/lib/python3.9/site-packages/eth/rlp/transactions.py", line 85, in sender
    return self.get_sender()
  File "/home/my_folder/py-evm/venv/lib/python3.9/site-packages/eth/vm/forks/frontier/transactions.py", line 101, in get_sender
    return extract_transaction_sender(self)
  File "/home/my_folder/py-evm/venv/lib/python3.9/site-packages/eth/_utils/transactions.py", line 98, in extract_transaction_sender
    signature = keys.Signature(vrs=vrs)
  File "/home/my_folder/py-evm/venv/lib/python3.9/site-packages/eth_keys/datatypes.py", line 382, in __init__
    raise BadSignature(str(error)) from error
eth_keys.exceptions.BadSignature: Value -27 is not greater than or equal to 0
```

How to solve this?

**Comment by fselmo** [comment]
Hey @pastet89... I'm not sure at all what's going on in the `recover_raw_transaction()` method you posted but it looks like whatever is happening you are getting `-27`, not `0` for `v`.

I'm also not sure why you chose `MuirGlacierTransaction` but it looks like the transaction you want was a typed transaction and those were not around in the Muir Glacier days.

You can get the result you want like so:

```py
from eth.vm.forks.arrow_glacier.transactions import ArrowGlacierTransactionBuilder
from eth_utils import (
  encode_hex,
  to_bytes,
)

>>> # the signed transaction to decode:
>>> original_hexstr = '0x784fed92b...'

>>> # convert the hex string to bytes:
>>> signed_tx_as_bytes = to_bytes(hexstr=original_hexstr)

>>> # deserialize the transaction using the latest transaction builder (Arrow Glacier at the time of writing, soon to be Gray Glacier):
>>> decoded_tx = ArrowGlacierTransactionBuilder().decode(signed_tx_as_bytes)
>>> decoded_tx.__dict__
{'type_id': 2, '_inner': DynamicFeeTransaction(chain_id=1, nonce=105, max_priority_fee_per_gas=1500000000, max_fee_per_gas=72882978399, 
gas=282986, to=b'\x7f&\x83W\xa8\xc2U&#1n%b\xd9\x0ed+\xb58\xe5', value=348900000000000000, data=b'\xab\x83K\xab\x00\x00...', access_list=(), 
y_parity=0, r=108128106577709960648360555828195390773825675124298788107033477245315938044442, s=43414734651983700962377115237100709991347317735197505540741341915840196120498)}

>>> # the (human-readable) sender's address:
>>> sender = encode_hex(decoded_tx.sender)
>>> sender
0x355a02...

```

Closing because this does not look like an issue but if you feel it is we can re-open. Best of luck.
