### ISSUE TITLE
lightshell sync from docs not working

### ISSUE THREAD

**Issue by step21** [ethereum/py-evm#295]
* py-evm Version: 0.6.0
* OS: Ubuntu 16.04.3
* Python Version (python --version): 3.5
* Environment (output of `pip freeze`):
aiohttp==2.3.1
apipkg==1.4
asn1crypto==0.24.0
async-generator==1.9
async-lru==0.1.0
async-timeout==2.0.0
attrs==17.4.0
bumpversion==0.5.3
cffi==1.11.4
chardet==3.0.4
coverage==4.4.2
cryptography==2.1.4
cytoolz==0.9.0
eth-bloom==0.5.2
eth-keys==0.1.0b3
eth-utils==0.7.4
execnet==1.5.0
flake8==3.5.0
hypothesis==3.30.0
idna==2.6
leveldb==0.194
mccabe==0.6.1
multidict==4.0.0
pluggy==0.6.0
py==1.5.2
py-ecc==1.4.2
-e git+git@github.com:pipermerriam/py-evm.git@8bc9a42943730fd09e29695dab0c2a1e869e913f#egg=py_evm
pycodestyle==2.3.1
pycparser==2.18
pyethash==0.1.27
pyflakes==1.6.0
pysha3==1.0.2
pytest==3.1.2
pytest-asyncio==0.8.0
pytest-cov==2.5.1
pytest-logging==2015.11.4
pytest-xdist==1.18.1
rlp==0.4.7
six==1.11.0
toolz==0.9.0
tox==2.7.0
trie==1.1.0
typing==3.6.2
virtualenv==15.1.0
yarl==1.1.0

### What is wrong?
According to docs, `python -i -m evm.lightchain_shell -db /home/florian/testnet.db` should work to sync the/a testnet. However it just errors out, with an additional error when force closing. I know that everything is still super pre-alpha or something, but still maybe it is useful and any pointers appreciated.

```
Logging to /tmp/lightchain-shell.log
>>> Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.5/asyncio/base_events.py", line 387, in run_until_complete
    return future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/usr/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "/home/florian/py-evm/evm/p2p/lightchain.py", line 289, in run
    asyncio.ensure_future(self.peer_pool.run())
  File "/usr/lib/python3.5/asyncio/tasks.py", line 546, in ensure_future
    loop = events.get_event_loop()
  File "/usr/lib/python3.5/asyncio/events.py", line 632, in get_event_loop
    return get_event_loop_policy().get_event_loop()
  File "/usr/lib/python3.5/asyncio/events.py", line 578, in get_event_loop
    % threading.current_thread().name)
RuntimeError: There is no current event loop in thread 'Thread-1'.


^CError in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/usr/lib/python3.5/asyncio/base_events.py", line 375, in run_until_complete
    self.run_forever()
  File "/usr/lib/python3.5/asyncio/base_events.py", line 345, in run_forever
    self._run_once()
  File "/usr/lib/python3.5/asyncio/base_events.py", line 1276, in _run_once
    event_list = self._selector.select(timeout)
  File "/usr/lib/python3.5/selectors.py", line 441, in select
    fd_event_list = self._epoll.poll(timeout, max_ev)
KeyboardInterrupt
sys:1: RuntimeWarning: coroutine 'PeerPool.run' was never awaited
```

**Comment by gsalgado** [comment]
I've just tested it with python 3.5.4 and it works as expected. Is your python version really just **3.5**, with no minor version?

**Comment by step21** [comment]
It's 3.5.2 actually. But I didn't think minor versions mattered much. Or at least shouldn't :)

**Comment by gsalgado** [comment]
It shouldn't, but given that the exception is coming from asyncio/events.py and that this works on 3.5.4, my first guess is that this is a python issue. And https://groups.google.com/forum/#!topic/vpython-users/WRc9Pz5LIio seems to support that

**Comment by step21** [comment]
Mmmm ok. Trying to install a newer one which seems to be a bit of a problem right now.

**Comment by gsalgado** [comment]
Going to close this as it seems to be an issue only present on python versions prior to 3.5.4
