### ISSUE TITLE
trinity crashes when attempting to run the database server

### ISSUE THREAD

**Issue by gsalgado** [ethereum/py-evm#398]
I get this traceback when I try to run trinity:

```
Traceback (most recent call last):
  File "/home/salgado/virtualenvs/pyevm/bin/trinity", line 11, in <module>
    load_entry_point('py-evm', 'console_scripts', 'trinity')()
  File "/home/salgado/src/py-evm/trinity/main.py", line 191, in main
    database_server_process.start()
  File "/usr/lib/python3.6/multiprocessing/process.py", line 105, in start
    self._popen = self._Popen(self)
  File "/usr/lib/python3.6/multiprocessing/context.py", line 284, in _Popen
    return Popen(process_obj)
  File "/usr/lib/python3.6/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/usr/lib/python3.6/multiprocessing/popen_fork.py", line 20, in __init__
    self._launch(process_obj)
  File "/usr/lib/python3.6/multiprocessing/popen_spawn_posix.py", line 47, in _launch
    reduction.dump(process_obj, fp)
  File "/usr/lib/python3.6/multiprocessing/reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
_pickle.PicklingError: Can't pickle <class 'abc.NativeECCBackendPrivateKey'>: attribute lookup NativeECCBackendPrivateKey on abc failed
```

**Comment by pipermerriam** [comment]
That makes sense.  Because of the dynamic class generation the `PrivateKey` objects returned by `eth-keys` aren't picklable.  This really needs to be fixed on the eth-keys side as the dynamic class generation is proving problematic.

**Comment by pipermerriam** [comment]
Odd that I haven't seen this error, anything non-standard going on? code changes?  hard coded private keys?

**Comment by pipermerriam** [comment]
link https://github.com/ethereum/eth-keys/issues/26

**Comment by pipermerriam** [comment]
proposed fix: https://github.com/ethereum/eth-keys/pull/36

**Comment by gsalgado** [comment]
No code changes, but I was passing a `nodekey` arg to trinity instead of using the nodekey-file

**Comment by pipermerriam** [comment]
that's something I think we should support, passing a *raw* nodekey via something like `--nodekey 0xabcd1234...`.

**Comment by gsalgado** [comment]
Right, and that works with your changes to eth-keys -- that's why I closed the issue
