### ISSUE TITLE
ChainSyncer: Stuck trying to sync Ropsten chain

### ISSUE THREAD

**Issue by cburgdorf** [ethereum/py-evm#543]
### What is wrong?

I tried syncing the ropsten chain via `python -m p2p.chain -db ~/path/to/db`

The hardcoded peers all seem not responding so I tried some other that I found mentioned somewhere.

```python
yield Node(keys.PublicKey(decode_hex("865a63255b3bb68023b6bffd5095118fcc13e79dcf014fe4e47e065c350c7cc72af2e53eff895f11ba1bbb6a2b33271c1116ee870f266618eadfc2e78aa7349c")),  # noqa: E501
                       Address("52.176.100.77", 30303, 30303))
yield Node(keys.PublicKey(decode_hex("6332792c4a00e3e4ee0926ed89e0d27ef985424d97b6a45bf0f23e51f0dcb5e66b875777506458aea7af6f9e4ffb69f43f3778ee73c81ed9d34c51c4b16b0b0f")),  # noqa: E501
                       Address("52.232.243.152", 30303, 30303))
```

Eventually I got a response from a parity node

```
19:39:48 DEBUG: Successfully decoded Hello (cmd_id=0) msg: {'version': 5, 'client_version_string': b'Parity/v1.9.2-beta-0feb0bb-20180201/x86_64-linux-gnu/rustc1.23.0', 'capabilities': ((b'eth', 62), (b'eth', 63), (b'par', 1), (b'par', 2), (b'pip', 1)), 'listen_port': 30303, 'remote_pubkey': b"\x86Zc%[;\xb6\x80#\xb6\xbf\xfdP\x95\x11\x8f\xcc\x13\xe7\x9d\xcf\x01O\xe4\xe4~\x06\\5\x0c|\xc7*\xf2\xe5>\xff\x89_\x11\xba\x1b\xbbj+3'\x1c\x11\x16\xee\x87\x0f&f\x18\xea\xdf\xc2\xe7\x8a\xa74\x9c"}
19:39:48 DEBUG: Finished P2P handshake with <Node(0x865a@52.176.100.77)>, using sub-protocol (eth, 63)
19:39:48 DEBUG: Sending ETH/Status msg: {'protocol_version': 63, 'network_id': 3, 'td': 6414977239101, 'best_hash': b'\x9f\x92\xe1/\x8a\x84\xea\x00C\xab\xa50T/\x90\xac,\x03\x92\x11\xb2\xccq\xef\xc4\xec\\7\xab+\x8b"', 'genesis_hash': b'A\x94\x10#h\t#\xe0\xfeMt\xa3K\xda\xc8\x14\x1f%@\xe3\xae\x90b7\x18\xe4}f\xd1\xcaJ-'}
```

However, that's as far as I got then. As I noticed there's a `min_peers` value so my naive guess is I'm stuck in limbo until I've found more peers. I tried to set the value to `1` to see if that would eventually cause it to try syncing the chain with that one lonely parity client that I got but so far that's not the case.

I also noticed this error coming up but aren't sure if that is related at all

```
19:50:49 ERROR: Unexpected error during auth/p2p handshake with <Node(0x6332@52.232.243.152)>
Traceback (most recent call last):
  File "/home/cburgdorf/Documents/hacking/ef/py-evm/p2p/peer.py", line 712, in connect
    timeout=HANDSHAKE_TIMEOUT)
  File "/home/cburgdorf/Documents/hacking/ef/py-evm/p2p/cancel_token.py", line 99, in wait_with_token
    return done.pop().result()
  File "/home/cburgdorf/Documents/hacking/ef/py-evm/p2p/peer.py", line 110, in handshake
    ) = await auth.handshake(remote, privkey)
  File "/home/cburgdorf/Documents/hacking/ef/py-evm/p2p/auth.py", line 52, in handshake
    initiator, reader, writer)
  File "/home/cburgdorf/Documents/hacking/ef/py-evm/p2p/auth.py", line 71, in _handshake
    ephemeral_pubkey, responder_nonce = initiator.decode_auth_ack_message(auth_ack)
  File "/home/cburgdorf/Documents/hacking/ef/py-evm/p2p/auth.py", line 169, in decode_auth_ack_message
    raise ValueError("Auth ack msg too short: {}".format(len(ciphertext)))
ValueError: Auth ack msg too short: 0
```

@gsalgado do you have any further pointers how to get this running?

**Comment by gsalgado** [comment]
https://github.com/ethereum/py-evm/pull/540 has more ropsten nodes

`ChainSyncer.min_peers_to_sync` is what defines how many peers are required in order for us to start a sync

The auth ack msg too short is a know issue, I think there's a FIXME but no open issue for it currently -- care to open one?

**Comment by cburgdorf** [comment]
Thank you! This is looking better now :tada: 

```
$ python -m p2p.chain -db ~cburgdorf/.local/share/trinity/ropsten/chain/
23:35:02 INFO: Running PeerPool...
23:35:18 INFO: Successfully connected to ETHPeer <Node(0xbbb3@81.169.153.213)>
23:35:18 INFO: Starting sync with ETHPeer <Node(0xbbb3@81.169.153.213)>
23:35:18 INFO: Fetching chain segment starting at #62290
23:35:18 INFO: Got headers segment starting at #62290
23:35:19 INFO: Got block bodies for chain segment starting at #62290
23:35:19 INFO: Got block receipts for chain segment starting at #62290
23:35:19 INFO: Imported chain segment, new head: #62481
23:35:19 INFO: Fetching chain segment starting at #62482
23:35:20 INFO: Got headers segment starting at #62482
23:35:20 INFO: Got block bodies for chain segment starting at #62482
23:35:21 INFO: Got block receipts for chain segment starting at #62482
23:35:21 INFO: Imported chain segment, new head: #62673
23:35:21 INFO: Fetching chain segment starting at #62674
23:35:21 INFO: Got headers segment starting at #62674
23:35:22 INFO: Got block bodies for chain segment starting at #62674
23:35:22 INFO: Got block receipts for chain segment starting at #62674
23:35:22 INFO: Imported chain segment, new head: #62865
23:35:22 INFO: Fetching chain segment starting at #62866
23:35:22 INFO: Got headers segment starting at #62866
23:35:23 INFO: Got block bodies for chain segment starting at #62866
23:35:23 INFO: Got block receipts for chain segment starting at #62866
23:35:23 INFO: Imported chain segment, new head: #63057
23:35:23 INFO: Fetching chain segment starting at #63058
23:35:24 INFO: Got headers segment starting at #63058
23:35:24 INFO: Got block bodies for chain segment starting at #63058
23:35:24 INFO: Got block receipts for chain segment starting at #63058
```

I faked this a little because I've set  `min_peers_to_sync` to `1` for this to start. Out of curiosity what's the reasoning for not starting to sync with the first connected peer right away?

I also created https://github.com/ethereum/py-evm/issues/544 so I'm closing this one.
