### ISSUE TITLE
Auth ack msg too short

### ISSUE THREAD

**Issue by cburgdorf** [ethereum/py-evm#544]
### What is wrong?

Trying to sync the Ropsten chain (`python -m p2p.chain -db ~/path/to/db`) I noticed this exception coming up.

```
19:50:49 ERROR: Unexpected error during auth/p2p handshake with <Node(0x6332@52.232.243.152)>
Traceback (most recent call last):
  File "/home/cburgdorf/Documents/hacking/ef/py-evm/p2p/peer.py", line 712, in connect
    timeout=HANDSHAKE_TIMEOUT)
  File "/home/cburgdorf/Documents/hacking/ef/py-evm/p2p/cancel_token.py", line 99, in wait_with_token
    return done.pop().result()
  File "/home/cburgdorf/Documents/hacking/ef/py-evm/p2p/peer.py", line 110, in handshake
    ) = await auth.handshake(remote, privkey)
  File "/home/cburgdorf/Documents/hacking/ef/py-evm/p2p/auth.py", line 52, in handshake
    initiator, reader, writer)
  File "/home/cburgdorf/Documents/hacking/ef/py-evm/p2p/auth.py", line 71, in _handshake
    ephemeral_pubkey, responder_nonce = initiator.decode_auth_ack_message(auth_ack)
  File "/home/cburgdorf/Documents/hacking/ef/py-evm/p2p/auth.py", line 169, in decode_auth_ack_message
    raise ValueError("Auth ack msg too short: {}".format(len(ciphertext)))
ValueError: Auth ack msg too short: 0
```

**Comment by gsalgado** [comment]
Closing in favour of #776
