### ISSUE TITLE
p2p tests have unclean finish

### ISSUE THREAD

**Issue by carver** [ethereum/py-evm#703]
### What is wrong?

p2p tests end with a bunch of repeats of this:

```
Error 'HTTPConnectionPool(host='192.168.1.250', port=49152): Max retries exceeded with url: /description.xml (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f256f014b00>: Failed to establish a new connection: [Errno 113] No route to host',))' for http://192.168.1.250:49152/description.xml
Error '404 Client Error: Not Found for url: http://192.168.2.44:8008/ssdp/notfound' for http://192.168.2.44:8008/ssdp/device-desc.xml
exception calling callback for <Future at 0x7f256e86dac8 state=finished returned list>
Traceback (most recent call last):
  File "/usr/lib/python3.6/concurrent/futures/_base.py", line 324, in _invoke_callbacks
    callback(self)
  File "/usr/lib/python3.6/asyncio/futures.py", line 419, in _call_set_state
    dest_loop.call_soon_threadsafe(_set_state, destination, source)
  File "/usr/lib/python3.6/asyncio/base_events.py", line 620, in call_soon_threadsafe
    self._check_closed()
  File "/usr/lib/python3.6/asyncio/base_events.py", line 357, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
```

### How can it be fixed

:man_shrugging:

**Comment by gsalgado** [comment]
We must not run `p2p.Server` in any of our tests, at least not without stubbing out stuff like the `refresh_nat_portmap()` coroutine, which is responsible for this. Related to #688 and #695

**Comment by gsalgado** [comment]
Well, to be precise we should avoid running p2p.Server at all costs, but if we have to we should stub out unnecessary bits and finish it properly to avoid those errors -- none of which is done by the existing sharding tests, though
