### ISSUE TITLE
division by zero in `FastChainSyncer`

### ISSUE THREAD

**Issue by pipermerriam** [ethereum/py-evm#726]
### What is wrong?

When the `PeerPool` has no peers we get a division by zero error.

```
Traceback (most recent call last):
  File "/Users/piper/sites/py-evm/p2p/chain.py", line 133, in sync
    await self._sync(peer)
  File "/Users/piper/sites/py-evm/p2p/chain.py", line 172, in _sync
    head_number = await self._process_headers(peer, headers)
  File "/Users/piper/sites/py-evm/p2p/chain.py", line 194, in _process_headers
    'receipt')
  File "/Users/piper/sites/py-evm/p2p/chain.py", line 229, in _download_block_parts
    pending_replies = request_func(missing)
  File "/Users/piper/sites/py-evm/p2p/chain.py", line 292, in request_receipts
    return self._request_block_parts(headers, self._send_get_receipts)
  File "/Users/piper/sites/py-evm/p2p/chain.py", line 260, in _request_block_parts
    length = math.ceil(len(headers) / len(self.peer_pool.peers))
ZeroDivisionError: division by zero
```

### How can it be fixed

TODO: how do we fix this

**Comment by pipermerriam** [comment]
@gsalgado should we do some sort of `await` for the peer pool till it has peers?

**Comment by gsalgado** [comment]
This is a race condition, I'm afraid. The chain syncer runs `sync()` in the background when it hears about a new peer/block, and it looks like by the time `sync()` got scheduled the `PeerPool` had lost all its peers. I guess we need to check for that at the beginning of `sync()` and abort if it's the case

**Comment by pipermerriam** [comment]
@gsalgado what do you think about https://github.com/ethereum/py-evm/pull/727
