### ISSUE TITLE
Base install of `py-evm` actually has `pytest` dependency

### ISSUE THREAD

**Issue by pipermerriam** [ethereum/py-evm#783]
### What is wrong?

```
Traceback (most recent call last):
  File "/home/ubuntu/py-evm/venv/bin/trinity", line 11, in <module>
    load_entry_point('py-evm', 'console_scripts', 'trinity')()
  File "/home/ubuntu/py-evm/venv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 542, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/ubuntu/py-evm/venv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2569, in load_entry_point
    return ep.load()
  File "/home/ubuntu/py-evm/venv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2229, in load
    return self.resolve()
  File "/home/ubuntu/py-evm/venv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2235, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/ubuntu/py-evm/trinity/__init__.py", line 10, in <module>
    from .main import (  # noqa: F401
  File "/home/ubuntu/py-evm/trinity/main.py", line 29, in <module>
    from trinity.chains import (
  File "/home/ubuntu/py-evm/trinity/chains/__init__.py", line 30, in <module>
    from trinity.config import (
  File "/home/ubuntu/py-evm/trinity/config.py", line 26, in <module>
    from trinity.nodes.base import (
  File "/home/ubuntu/py-evm/trinity/nodes/base.py", line 13, in <module>
    from trinity.rpc.main import (
  File "/home/ubuntu/py-evm/trinity/rpc/__init__.py", line 1, in <module>
    from .main import RPCServer  # noqa: F401
  File "/home/ubuntu/py-evm/trinity/rpc/main.py", line 9, in <module>
    from trinity.rpc.modules import (
  File "/home/ubuntu/py-evm/trinity/rpc/modules/__init__.py", line 4, in <module>
    from .evm import EVM  # noqa: F401
  File "/home/ubuntu/py-evm/trinity/rpc/modules/evm.py", line 5, in <module>
    from evm.tools.fixture_tests import (
  File "/home/ubuntu/py-evm/evm/tools/fixture_tests.py", line 10, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
```

### How can it be fixed

Move `pytest` imports to within the function contexts that use them so that pytest isn't a hard dependency.  Wrap these imports in a `try/except` and raise a friendly error message when `pytest` is not available for import.

> The <function-name> tool requires pytest.  Please install the pytest library

**Comment by cburgdorf** [comment]
Fixed with https://github.com/ethereum/py-evm/commit/86e608ca1ab1c781dad549e9caa2579171db863f
