### ISSUE TITLE
Trinity throws HeaderNotFound error.

### ISSUE THREAD

**Issue by pipermerriam** [ethereum/py-evm#803]
### What is wrong?

```
   ERROR  05-28 23:10:05  base_events  Task exception was never retrieved
future: <Task finished coro=<FastChainSyncer.sync() done, defined at /Users/piper/sites/py-evm/p2p/chain.py:161> exception=HeaderNotFound('No header with hash 0x9a9f86051d5b58d5d682d90b84e34f822671b13a9d3dac579d181b566be6a32f found',)>
Traceback (most recent call last):
  File "/Users/piper/sites/py-evm/p2p/chain.py", line 174, in sync
    await self._sync(peer)
  File "/Users/piper/sites/py-evm/p2p/chain.py", line 220, in _sync
    head_number = await self._process_headers(peer, headers)
  File "/Users/piper/sites/py-evm/p2p/chain.py", line 233, in _process_headers
    'body')
  File "/Users/piper/sites/py-evm/p2p/chain.py", line 297, in _download_block_parts
    pending_replies = request_func(missing)
  File "/Users/piper/sites/py-evm/p2p/chain.py", line 361, in request_bodies
    return self._request_block_parts(headers, self._send_get_block_bodies)
  File "/Users/piper/sites/py-evm/p2p/chain.py", line 335, in _request_block_parts
    target_td = self.chaindb.get_score(headers[0].parent_hash)
  File "/Users/piper/sites/py-evm/trinity/utils/mp.py", line 30, in method
    return self._callmethod(method_name, args, kwargs)
  File "/Users/piper/.pyenv/versions/3.6.3/lib/python3.6/multiprocessing/managers.py", line 772, in _callmethod
    raise convert_to_error(kind, result)
evm.exceptions.HeaderNotFound: No header with hash 0x9a9f86051d5b58d5d682d90b84e34f822671b13a9d3dac579d181b566be6a32f found
```

**Comment by gsalgado** [comment]
This happens because `_request_block_parts()` is called multiple times, with subsets of the header batch originally passed to `_process_headers()`, but we can only assume our DB contains the header for the parent of the first item in the batch originally passed to `_process_headers()`
