### ISSUE TITLE
Unhandled KeyboardInterrupt exceptions on Unix when using the spawn start method for multiprocessing

### ISSUE THREAD

**Issue by gsalgado** [ethereum/py-evm#863]
### What is wrong?

When using the `spawn` method (our default) for the multiprocessing module, I often get a bunch of unhandled KeyboardInterrupt exceptions when I Ctrl+C trinity. If using `TRINITY_MP_CONTEXT=fork` I never seem to get those

```
    INFO  06-04 15:06:13       chain  Imported 192 headers in 2.25 seconds, new head: #1346212 (1cd32f)                                                                         
^C    INFO  06-04 15:06:14        main  Keyboard Interrupt: Stopping                                                                                                            
Process Process-2:3:                                                                                                                                                            
Process Process-2:1:                                                                                                                                                            
    INFO  06-04 15:06:14         ipc  Sent SIGINT to process 27860, waiting 5 seconds for it to terminate                                                                       
Process Process-2:2:                                                                                                                                                            
Traceback (most recent call last):                                                                                                                                              
  File "/usr/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap                                                                                                 
    self.run()                                                                                                                                                                  
  File "/usr/lib/python3.6/multiprocessing/process.py", line 93, in run                                                                                                         
    self._target(*self._args, **self._kwargs)                                                                                                                                   
  File "/usr/lib/python3.6/concurrent/futures/process.py", line 169, in _process_worker                                                                                         
    call_item = call_queue.get(block=True)                                                                                                                                      
  File "/usr/lib/python3.6/multiprocessing/queues.py", line 93, in get                                                                                                          
    with self._rlock:                                                                                                                                                           
  File "/usr/lib/python3.6/multiprocessing/synchronize.py", line 96, in __enter__                                                                                               
    return self._semlock.__enter__()                                                                                                                                            
KeyboardInterrupt                                                                                                                                                               
Traceback (most recent call last):                                                                                                                                              
  File "/usr/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap                                                                                                 
    self.run()                                                                                                                                                                  
  File "/usr/lib/python3.6/multiprocessing/process.py", line 93, in run                                                                                                         
    self._target(*self._args, **self._kwargs)                                                                                                                                   
  File "/usr/lib/python3.6/concurrent/futures/process.py", line 169, in _process_worker                                                                                         
    call_item = call_queue.get(block=True)                                                                                                                                      
  File "/usr/lib/python3.6/multiprocessing/queues.py", line 94, in get                                                                                                          
    res = self._recv_bytes()                                                                                                                                                    
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 216, in recv_bytes                                                                                              
    buf = self._recv_bytes(maxlength)                                                                                                                                           
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 407, in _recv_bytes                                                                                             
    buf = self._recv(4)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 379, in _recv
    chunk = read(handle, remaining)
KeyboardInterrupt
```

it looks like the kind of thing that would be caused by the [multiprocessing module](https://docs.python.org/3.6/library/multiprocessing.html#multiprocessing.Semaphore):

> If the SIGINT signal generated by Ctrl-C arrives while the main thread is blocked by a call to BoundedSemaphore.acquire(),
Lock.acquire(), RLock.acquire(), Semaphore.acquire(), Condition.acquire() or Condition.wait() then the call will be immediately
interrupted and KeyboardInterrupt will be raised.

**Comment by pipermerriam** [comment]
In trying to remember why `spawn` was chosen, this is the best I could find.

https://docs.python.org/3.6/library/multiprocessing.html#contexts-and-start-methods

If we use `fork` it looks like we won't be usable on windows platforms.

**Comment by pipermerriam** [comment]
Fixed in https://github.com/ethereum/py-evm/pull/1177
