### ISSUE TITLE
Trinity throws decryption error: Invalid Frame mac

### ISSUE THREAD

**Issue by pipermerriam** [ethereum/py-evm#881]
### What is wrong?

```python
   ERROR  06-07 01:02:55     service  Unexpected error in ETHPeer <Node(0xa4d6@116.232.43.101)>, exiting
Traceback (most recent call last):
  File "/home/ubuntu/py-evm/p2p/service.py", line 68, in run
    await self._run()
  File "/home/ubuntu/py-evm/p2p/peer.py", line 311, in _run
    cmd, msg = await self.read_msg()
  File "/home/ubuntu/py-evm/p2p/peer.py", line 331, in read_msg
    msg = self.decrypt_body(frame_data, frame_size)
  File "/home/ubuntu/py-evm/p2p/peer.py", line 431, in decrypt_body
    raise DecryptionError('Invalid frame mac')
p2p.exceptions.DecryptionError: Invalid frame mac
```

This escaped today while running my trinity node.

**Comment by gsalgado** [comment]
Care to include other log lines relating to the same peer? Maybe something there will shed a light on what could be going on

**Comment by pipermerriam** [comment]
```
   ERROR  05-19 20:06:19    service  Unexpected error in ETHPeer <Node(0x3f56@52.187.147.199)>, exiting
Traceback (most recent call last):
  File "/Users/piper/sites/py-evm/p2p/service.py", line 34, in run
    await self._run()
  File "/Users/piper/sites/py-evm/p2p/peer.py", line 292, in _run
    cmd, msg = await self.read_msg()
  File "/Users/piper/sites/py-evm/p2p/peer.py", line 312, in read_msg
    msg = self.decrypt_body(frame_data, frame_size)
  File "/Users/piper/sites/py-evm/p2p/peer.py", line 408, in decrypt_body
    raise DecryptionError('Invalid frame mac')
p2p.exceptions.DecryptionError: Invalid frame mac
```

Grepping logs for `0x3f56`

```
full-sync-4.log:    INFO  05-19 20:06:17       peer  Successfully connected to ETHPeer <Node(0x3f56@52.187.147.199)>
full-sync-4.log:   ERROR  05-19 20:06:19    service  Unexpected error in ETHPeer <Node(0x3f56@52.187.147.199)>, exiting
trinity-HeaderNotFound.log:   DEBUG  06-01 22:30:18        peer  Connecting to <Node(0x3f56@52.187.147.199)>...
trinity-HeaderNotFound.log:   DEBUG  06-01 22:30:19        peer  Could not complete handshake with <Node(0x3f56@52.187.147.199)>: HandshakeFailure('ETHPeer <Node(0x3f56@52.187.147.199)> disconnected before completing handshake: too_many_peers',)
trinity-HeaderNotFound.log:   DEBUG  06-02 00:03:41        peer  Connecting to <Node(0x3f56@52.187.147.199)>...
trinity-HeaderNotFound.log:   DEBUG  06-02 00:03:44        peer  Could not complete handshake with <Node(0x3f56@52.187.147.199)>: UnreachablePeer(TimeoutError(),)
trinity-HeaderNotFound.log:   DEBUG  06-02 02:45:35        peer  Connecting to <Node(0x3f56@52.187.147.199)>...
trinity-HeaderNotFound.log:   DEBUG  06-02 02:45:36        peer  Could not complete handshake with <Node(0x3f56@52.187.147.199)>: HandshakeFailure('ETHPeer <Node(0x3f56@52.187.147.199)> disconnected before completing handshake: too_many_peers',)
trinity-HeaderNotFound.log:   DEBUG  06-02 03:22:44        peer  Connecting to <Node(0x3f56@52.187.147.199)>...
trinity-HeaderNotFound.log:   DEBUG  06-02 03:22:45        peer  Could not complete handshake with <Node(0x3f56@52.187.147.199)>: HandshakeFailure('ETHPeer <Node(0x3f56@52.187.147.199)> disconnected before completing handshake: too_many_peers',)
```

Nothing that interesting.  Raw log here: https://gist.github.com/pipermerriam/f33802d8d8890af3c6c7a128e2745e75/raw/dde2e7b06cd09e99f0f7d465b2097a00741ce9aa/full-sync-4.log

**Comment by gsalgado** [comment]
In the logs I have here (~500M) there's no occurrences of that, but there's no entries for that peer in them either. Also, since it happens immediately after connecting to the peer, I suspect it'd be something specific to that peer. If you're still seeing this, @pipermerriam, can you get the full node id for the peer (should be logged now) so that I can try and reproduce

Also, maybe this should not be on the Grace Hopper milestone?

**Comment by pipermerriam** [comment]
Closing for now.  we can re-open if it shows back up.
