### ISSUE TITLE
Trinity throws MalformedMessage

### ISSUE THREAD

**Issue by pipermerriam** [ethereum/py-evm#882]
### What is wrong?

This is escaping unhandled during runs of trinity.

```python
   ERROR  06-07 03:32:06      server  Unexpected error handling handshake
Traceback (most recent call last):
  File "/home/ubuntu/py-evm/p2p/p2p_proto.py", line 59, in decode
    raw_decoded = cast(Dict[str, int], super(Disconnect, self).decode(data))
  File "/home/ubuntu/py-evm/p2p/protocol.py", line 95, in decode
    return self.decode_payload(data[1:])
  File "/home/ubuntu/py-evm/p2p/protocol.py", line 82, in decode_payload
    data = rlp.decode(rlp_data, sedes=decoder)
  File "/home/ubuntu/py-evm/venv/lib/python3.6/site-packages/rlp/codec.py", line 220, in decode
    obj = sedes.deserialize(item, **kwargs)
  File "/home/ubuntu/py-evm/venv/lib/python3.6/site-packages/eth_utils/functional.py", line 22, in inner
    return callback(fn(*args, **kwargs))
  File "/home/ubuntu/py-evm/venv/lib/python3.6/site-packages/rlp/sedes/lists.py", line 84, in deserialize
    raise ListDeserializationError('List has wrong length', serial)
rlp.exceptions.ListDeserializationError: List has wrong length

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/py-evm/p2p/server.py", line 287, in receive_handshake
    await self._receive_handshake(reader, writer)
  File "/home/ubuntu/py-evm/p2p/server.py", line 363, in _receive_handshake
    await self.wait(self.do_handshake(peer))
  File "/home/ubuntu/py-evm/p2p/service.py", line 32, in wait
    return await self.wait_first(awaitable, token=token, timeout=timeout)
  File "/home/ubuntu/py-evm/p2p/service.py", line 51, in wait_first
    return await wait_with_token(*awaitables, token=token_chain, timeout=timeout)
  File "/home/ubuntu/py-evm/p2p/cancel_token.py", line 119, in wait_with_token
    return done.pop().result()
  File "/home/ubuntu/py-evm/p2p/server.py", line 366, in do_handshake
    await peer.do_p2p_handshake(),
  File "/home/ubuntu/py-evm/p2p/peer.py", line 242, in do_p2p_handshake
    cmd, msg = await self.read_msg()
  File "/home/ubuntu/py-evm/p2p/peer.py", line 337, in read_msg
    decoded_msg = cmd.decode(msg)
  File "/home/ubuntu/py-evm/p2p/p2p_proto.py", line 62, in decode
    raise MalformedMessage("Malformed Disconnect message: {0}".format(data))
p2p.exceptions.MalformedMessage: Malformed Disconnect message: b'\x01\xf8y\x05\xa7odash/v1.0.0-stable/linux-amd64/go1.8.3\xcc\xc5\x83eth?\xc5\x83eth>\x80\xb8@\xd74\xeb\xdd\x82\xd8\xee"\x86>\xd3\xa7v\xabm\xdfe\x9cJ\xfeR8\xab!\xab\xa5b\x80\xdfK\x83\xfbkL\x0f\xc5\x7f+\\\xea2\xd2\x11\x1e\xa9\xefL\x19\xa6<\xa9^u\x02\xfcl\xf3~\x10H\xca|1Q'
```

### How can it be fixed

Exception should be handled.

**Comment by gsalgado** [comment]
Reopened because of https://github.com/ethereum/py-evm/pull/924/files#r197480293
