### ISSUE TITLE
Block importing crashes with KeyError when validating uncles

### ISSUE THREAD

**Issue by gsalgado** [ethereum/py-evm#954]
### What is wrong?

When validating a newly imported block, we do a `self.get_vm(uncle)` for every uncle of the block, but that will crash when the uncle has not been previously persisted to the DB. That happens because the `get_vm()` call will try to load the uncle's transactions from the DB and will crash with a KeyError when those are not found. This is a regression that has been introduced by #740 -- before that we didn't have the `self.get_vm(uncle)` call as we were using the imported block's VM to perform the uncle validation

### How can it be fixed

Not sure

**Comment by gsalgado** [comment]
This is how it shows up in the logs: 

```
   ERROR  06-23 08:26:27  base_events  Task exception was never retrieved
future: <Task finished coro=<FastChainSyncer.sync() done, defined at /home/salgado/src/py-evm/p2p/chain.py:122> exception=KeyError(b'(e\xed\x84\xeark\xf1\x8c\x9d\xb8/\xce\x9f\x
a0l\xe8\x11\xef\x88\x83\x933<4\xab\x15{\xc9+\xfa1',)>
Traceback (most recent call last):
  File "/home/salgado/src/py-evm/p2p/chain.py", line 135, in sync
    await self._sync(peer)
  File "/home/salgado/src/py-evm/p2p/chain.py", line 184, in _sync
    head_number = await self._process_headers(peer, headers)
  File "/home/salgado/src/py-evm/p2p/chain.py", line 610, in _process_headers
    await self.wait(self.chain.coro_import_block(block, perform_validation=True))
  File "/home/salgado/src/py-evm/p2p/service.py", line 32, in wait
    return await self.wait_first(awaitable, token=token, timeout=timeout)
  File "/home/salgado/src/py-evm/p2p/service.py", line 51, in wait_first
    return await wait_with_token(*awaitables, token=token_chain, timeout=timeout)
  File "/home/salgado/src/py-evm/p2p/cancel_token.py", line 119, in wait_with_token
    return done.pop().result()
  File "/home/salgado/src/py-evm/trinity/utils/mp.py", line 27, in method
    args,
  File "/usr/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/lib/python3.6/multiprocessing/managers.py", line 772, in _callmethod
    raise convert_to_error(kind, result)
KeyError: b'(e\xed\x84\xeark\xf1\x8c\x9d\xb8/\xce\x9f\xa0l\xe8\x11\xef\x88\x83\x933<4\xab\x15{\xc9+\xfa1'
```
